import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { HAND_WRITTEN, staleRoutes } from '../scripts/build-routes.ts';

const ROOT = join(import.meta.dir, '..');
const SRC = join(ROOT, 'src');
const ROUTE = join(SRC, 'routes', 'dashboard', '$guildId', 'commands.tsx');

function source(file: string): string {
  return readFileSync(join(SRC, file), 'utf8');
}

function declaration(file: string, name: string): string {
  const text = source(file);
  const start = text.indexOf(`export const ${name} = `);
  const next = text.indexOf('\nexport ', start + 1);

  expect(start).toBeGreaterThanOrEqual(0);

  return text.slice(start, next === -1 ? undefined : next);
}

describe('the Commands server functions', () => {
  test('reading the catalogue is a GET behind the guild access check', () => {
    const declared = declaration('server/commands.ts', 'getGuildCommands');

    expect(declared).toContain("createServerFn({ method: 'GET' })");
    expect(declared).toContain('.middleware([requireGuildAccess])');
    expect(declared).toContain('api.getCommands(data.guildId)');
  });

  test.each([
    ['updateGuildCommand', 'api.updateCommand(guildId, key, { ...input, ...stamp })'],
    [
      'setGuildCommandEnabled',
      'api.setCommandEnabled(data.guildId, data.key, { enabled: data.enabled, ...stamp })',
    ],
    ['ackLostCommandPermissions', 'api.ackLostCommandPermissions(data.guildId, stamp)'],
  ])('%s is a POST behind Manage Server, stamped for the audit trail', (name, call) => {
    const declared = declaration('server/commands.ts', name);

    expect(declared).toContain("createServerFn({ method: 'POST' })");
    expect(declared).toContain('.middleware([requireManageGuild])');
    expect(declared).not.toContain('requireGuildAccess');
    expect(declared).toContain('withAudit(context.session.user.id, (stamp) =>');
    expect(declared.replace(/\s+/g, ' ')).toContain(call);
  });

  test('the save and switch validators come from core’s bodies, without the stamp', () => {
    const text = source('server/commands.ts');

    expect(text).toContain('commandUpdateBodySchema.omit(stampFields).extend(commandTarget)');
    expect(text).toContain('commandEnabledBodySchema.omit(stampFields).extend(commandTarget)');
    expect(text).toContain('const stampFields = { actorId: true, source: true, ipHash: true }');
  });

  test('the page reads and writes through those server functions', () => {
    expect(source('lib/queries.ts')).toContain("from '../server/commands.ts';");
    expect(source('lib/query-keys.ts')).toContain(
      "commands: (guildId: string) => ['guild', guildId, 'commands'] as const",
    );
  });
});

describe('the Commands route', () => {
  test('is hand-written, with its own loader and a header shown at once', () => {
    const route = readFileSync(ROUTE, 'utf8');

    expect(route).not.toContain('Generated by scripts/build-routes.ts');
    expect(route).toContain("createFileRoute('/dashboard/$guildId/commands')");
    expect(route).toContain('loadCommands(context.queryClient, params.guildId, preload)');
    expect(route).toContain('pendingMs: 0');
    expect(route).toContain('pendingComponent: CommandsPending');
  });

  test('survives the module route generator’s sweep of stale files', () => {
    expect(HAND_WRITTEN.has('commands')).toBe(true);
    expect(staleRoutes(['commands.tsx', 'index.tsx', 'tags.tsx', 'retired.tsx'])).toEqual([
      'retired',
    ]);
    expect(existsSync(join(SRC, 'pages', 'commands.tsx'))).toBe(true);
  });

  test('is in the generated route tree', () => {
    expect(source('routeTree.gen.ts')).toContain("'/dashboard/$guildId/commands'");
  });

  test('the public reference says what decides whether a command appears', () => {
    const lede = source('routes/commands.tsx').replace(/\s+/g, ' ');

    expect(lede).not.toContain('only appears in your server once its module is enabled');
    expect(lede).toContain(
      'A command appears in your server once its module is on, and you can rename commands or ' +
        'turn them off on the dashboard’s Commands page. /help stays available even with every ' +
        'module off.',
    );
  });

  test('the sidebar and the overview link to it, and the public reference stays in the site nav', () => {
    expect(source('components/shell/sidebar.tsx')).toContain('to="/dashboard/$guildId/commands"');
    expect(source('routes/dashboard/$guildId/index.tsx')).toContain(
      'to="/dashboard/$guildId/commands"',
    );
    expect(source('components/site/chrome.tsx')).toContain('to="/commands"');
  });
});

describe('the Commands page’s imports', () => {
  test('the dialog and rows import nothing that reaches the server', () => {
    for (const file of [
      'pages/commands/editor.tsx',
      'pages/commands/rows.tsx',
      'pages/commands/draft.ts',
      'pages/commands/list.ts',
    ]) {
      const text = source(file);

      expect(text).not.toMatch(/from '[^']*\/server\//);
      expect(text).not.toMatch(/from '[^']*lib\/queries\.ts'/);
    }
  });

  test('chrome.tsx still never imports the query module', () => {
    expect(source('components/site/chrome.tsx')).not.toMatch(/from '[^']*lib\/queries\.ts'/);
  });
});
