export {
  accountAgeProvider,
  CORE_MODULE_ID,
  CORE_PROVIDER_IDS,
  CORE_PROVIDERS,
  hasAvatarProvider,
  hasRoleProvider,
  isBoosterProvider,
  isPremiumProvider,
  lacksRoleProvider,
  memberAgeProvider,
} from './builtins.ts';
export {
  DEFAULT_CHUNK_SIZE,
  type DegradedProvider,
  describeMultipliers,
  describeRequirements,
  type EntryBreakdown,
  type EntryWeight,
  type EvaluateOptions,
  evaluateMultipliers,
  evaluateRequirement,
  evaluateRequirements,
  evaluateWeight,
  MULTIPLIER_MODES,
  type MultiplierMode,
  type MultiplierSpec,
  type RequirementFailure,
  type RequirementSpec,
  type RequirementVerdict,
  type WeightOptions,
} from './evaluate.ts';
export {
  absentMemberContext,
  createdAtOf,
  type MemberContextLoader,
  memberContextFromGuildMember,
  memberContextFromRuleFacts,
  StaticMemberContextLoader,
} from './member-context.ts';
export {
  type AvailableProvider,
  type ParseConfigResult,
  PROVIDER_BUILDER_MAX,
  type ProviderOwner,
  ProviderRegistrationError,
  ProviderRegistry,
} from './registry.ts';
export {
  BulkMemberContextLoader,
  MEMBER_PAGE_MAX,
  type MemberLoaderOptions,
  RestMemberContextLoader,
} from './rest-member-context.ts';
export {
  type ConditionProgress,
  type ConditionProvider,
  type ConditionResult,
  DEFAULT_LOCALE,
  isConditionProvider,
  isMultiplierProvider,
  type MemberContext,
  type ModuleAvailability,
  type MultiplierProvider,
  type Provider,
  type ProviderCost,
  type ProviderKind,
  type ProviderSchema,
} from './types.ts';
