// Generated by scripts/build-routes.ts. Do not edit by hand.
// Re-run with `bun run build:routes` after adding a module to the catalogue.

import { createFileRoute } from '@tanstack/react-router';
import { zodValidator } from '@tanstack/zod-adapter';
import { ModulePending } from '../../../components/module/pending.tsx';
import { ModuleRoute, moduleSearchSchema } from '../../../components/module/route.tsx';
import { loadModule } from '../../../lib/modules/preload.ts';
import Page from '../../../pages/leveling.tsx';

export const Route = createFileRoute('/dashboard/$guildId/leveling')({
  loader: ({ context, params, preload, location }) =>
    loadModule(context.queryClient, params.guildId, 'leveling', preload, location.search),
  validateSearch: zodValidator(moduleSearchSchema),
  // 0, not 1000 and 500: a click waiting on the page or its settings shows this header at once.
  pendingMs: 0,
  pendingMinMs: 0,
  pendingComponent: () => <ModulePending moduleId="leveling" />,
  component: () => <ModuleRoute moduleId="leveling" page={Page} />,
});
