import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');

export const GENERATED_PATH = join(ROOT, 'src', 'components', 'module', 'registry.ts');

export function generate(): string {
  return `// Generated by scripts/build-registry.ts. Do not edit by hand.

import type { ModuleSummary } from '@proton/core';
import type { ComponentType } from 'react';
import type { ModuleMeta } from '../../lib/modules/catalogue.ts';

export interface ModulePageProps {
  guildId: string;
  meta: ModuleMeta;
  summary: ModuleSummary | undefined;
  area: string;
}

export type ModulePage = ComponentType<ModulePageProps>;
`;
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, generate(), 'utf8');
  console.log(`wrote ${GENERATED_PATH}`);
}
