import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import groups from 'unicode-emoji-json/data-by-group.json' with { type: 'json' };

const ROOT = join(import.meta.dir, '..');
export const GENERATED_PATH = join(ROOT, 'src', 'components', 'discord', 'emoji-set.gen.ts');

interface SourceEmoji {
  emoji: string;
  name: string;
  slug: string;
}

interface SourceGroup {
  slug: string;
  emojis: SourceEmoji[];
}

/**
 * The categories, in Discord's order rather than Unicode's — Discord shows Activities before Travel
 * and every admin picking an emoji here has used that picker. The icon is a representative emoji
 * rather than a drawn glyph, which is also what Discord's rail does.
 */
const GROUPS: readonly { source: string; id: string; label: string; icon: string }[] = [
  { source: 'smileys_emotion', id: 'smileys', label: 'Smileys & Emotion', icon: '😀' },
  { source: 'people_body', id: 'people', label: 'People & Body', icon: '👋' },
  { source: 'animals_nature', id: 'nature', label: 'Animals & Nature', icon: '🐻' },
  { source: 'food_drink', id: 'food', label: 'Food & Drink', icon: '🍔' },
  { source: 'activities', id: 'activities', label: 'Activities', icon: '⚽' },
  { source: 'travel_places', id: 'travel', label: 'Travel & Places', icon: '✈️' },
  { source: 'objects', id: 'objects', label: 'Objects', icon: '💡' },
  { source: 'symbols', id: 'symbols', label: 'Symbols', icon: '🔣' },
  { source: 'flags', id: 'flags', label: 'Flags', icon: '🏳️' },
];

// A single quote inside a name would close the string literal this emits. No Unicode CLDR name has
// one today, so this is a guard against a future data update rather than a case being handled.
function literal(value: string): string {
  if (value.includes("'") || value.includes('\\')) {
    throw new Error(`emoji name '${value}' needs escaping this generator does not do`);
  }

  return `'${value}'`;
}

export function generate(): string {
  const source = groups as unknown as SourceGroup[];
  const byGroup = new Map(source.map((group) => [group.slug, group.emojis]));

  const body = GROUPS.map((group) => {
    const emojis = byGroup.get(group.source);
    if (!emojis) throw new Error(`unicode-emoji-json has no '${group.source}' group`);

    // Name and char only. The dataset also carries slugs and version fields, and this file ships to
    // the browser — the picker searches names and prints them, and needs nothing else.
    const rows = emojis
      .map((emoji) => `      { char: '${emoji.emoji}', name: ${literal(emoji.name)} },`)
      .join('\n');

    return [
      '  {',
      `    id: '${group.id}',`,
      `    label: ${literal(group.label)},`,
      `    icon: '${group.icon}',`,
      '    emojis: [',
      rows,
      '    ],',
      '  },',
    ].join('\n');
  }).join('\n');

  const header = [
    '// Generated by scripts/build-emoji.ts from unicode-emoji-json. Do not edit by hand.',
    '// Re-run with `bun run build:emoji` after bumping that dependency.',
  ].join('\n');

  const types = [
    'export interface UnicodeEmoji {',
    '  readonly char: string;',
    '  readonly name: string;',
    '}',
    '',
    'export interface UnicodeEmojiGroup {',
    '  readonly id: string;',
    '  readonly label: string;',
    '  readonly icon: string;',
    '  readonly emojis: readonly UnicodeEmoji[];',
    '}',
  ].join('\n');

  return `${header}\n\n${types}\n\nexport const EMOJI_GROUPS: readonly UnicodeEmojiGroup[] = [\n${body}\n];\n`;
}

if (import.meta.main) {
  const output = generate();
  writeFileSync(GENERATED_PATH, output, 'utf8');

  const count = (output.match(/\{ char: /g) ?? []).length;
  console.log(`wrote ${count} emoji in ${GROUPS.length} groups to ${GENERATED_PATH}`);
}
