import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CHANNEL_ICON_NAMES } from '../src/components/form/fields.tsx';
import { AREA_ICON_NAMES } from '../src/components/module/area-index.ts';
import {
  ACTION_ICON_NAMES,
  BROWSE_VIEWS,
  CATEGORY_ICONS,
  MODULE_ICON_NAMES,
} from '../src/components/shell/module-meta.ts';

const ROOT = join(import.meta.dir, '..');
const SRC = join(ROOT, 'src');
const ASSETS = join(ROOT, 'node_modules', '@phosphor-icons', 'core', 'assets');
export const GENERATED_PATH = join(SRC, 'components', 'shell', 'icon-set.gen.ts');

const WEIGHTS = ['regular', 'fill'] as const;

function sourceFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);

    if (entry.isDirectory()) sourceFiles(full, out);
    else if (/\.tsx?$/.test(entry.name) && !entry.name.endsWith('.gen.ts')) out.push(full);
  }

  return out;
}

/**
 * Every name an <Icon> can be handed. The JSX literals have to be scraped rather than imported —
 * they are spelled inline at the call site — but a name this misses becomes a type error at the
 * call site rather than a blank square in the browser, because Icon takes IconName, not string.
 */
export function renderableNames(): string[] {
  // The closed tables that turn something else's vocabulary into an icon. A table added without
  // being listed here fails `bun run typecheck`, because its values stop being an IconName.
  const names = new Set<string>([
    ...Object.values(CATEGORY_ICONS),
    ...MODULE_ICON_NAMES,
    ...ACTION_ICON_NAMES,
    ...CHANNEL_ICON_NAMES,
    ...AREA_ICON_NAMES,
    ...BROWSE_VIEWS.map((view) => view.icon),
  ]);

  for (const file of sourceFiles(SRC)) {
    if (file === GENERATED_PATH) continue;

    for (const tag of readFileSync(file, 'utf8').matchAll(/<Icon\b[\s\S]*?\/>/g)) {
      const prop = /name=(\{[\s\S]*?\}|"[a-z0-9-]+")/.exec(tag[0]);
      if (!prop?.[1]) throw new Error(`an <Icon> in ${file} has no name prop this can read`);

      const expression = prop[1];

      if (expression.startsWith('"')) {
        names.add(expression.slice(1, -1));
        continue;
      }

      // A ternary picking an icon by comparing something to a string puts that something's value
      // in the same expression: name={sort.direction === 'asc' ? 'caret-up' : 'caret-down'}.
      const branches = expression
        .replace(/[=!]==?\s*'[a-z0-9-]+'/g, '')
        .replace(/'[a-z0-9-]+'\s*[=!]==?/g, '');

      for (const literal of branches.matchAll(/'([a-z0-9-]+)'/g)) names.add(literal[1] ?? '');
    }
  }

  return [...names].filter(Boolean).sort();
}

function glyph(name: string, weight: (typeof WEIGHTS)[number]): string {
  const file = join(ASSETS, weight, weight === 'fill' ? `${name}-fill.svg` : `${name}.svg`);

  let svg: string;
  try {
    svg = readFileSync(file, 'utf8');
  } catch {
    throw new Error(
      `Phosphor has no '${name}' in ${weight}. Check the spelling against ${ASSETS}.`,
    );
  }

  const paths = [...svg.matchAll(/<path d="([^"]+)"\s*\/>/g)].map((match) => match[1] ?? '');

  // Every Phosphor glyph in this set is one path, so the generated module can hold path data
  // rather than markup and Icon can render a <path> instead of setting innerHTML.
  if (paths.length !== 1 || !paths[0]) {
    throw new Error(`${file} is not the single <path> this generator emits (${paths.length})`);
  }

  return paths[0];
}

export function generate(): string {
  const body = renderableNames()
    .map((name) => {
      const weights = WEIGHTS.map((w) => `    ${w}: '${glyph(name, w)}',`).join('\n');

      return `  '${name}': {\n${weights}\n  },`;
    })
    .join('\n');

  const header = [
    '// Generated by scripts/build-icons.ts from @phosphor-icons/core. Do not edit by hand.',
    '// Re-run with `bun run build:icons` after adding an <Icon name> or a module-meta entry.',
  ].join('\n');

  return `${header}\n\nexport const ICONS = {\n${body}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`;
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, generate(), 'utf8');

  console.log(
    `wrote ${renderableNames().length} icons in ${WEIGHTS.length} weights to ${GENERATED_PATH}`,
  );
}
