import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { permissionNames } from '@proton/core';
import { MODULES } from '@proton/modules';

const ROOT = join(import.meta.dir, '..');
export const GENERATED_PATH = join(ROOT, 'src', 'components', 'site', 'command-set.gen.ts');

const SUB_COMMAND = 1;
const SUB_COMMAND_GROUP = 2;

// Structural, not discord-api-types: that package's option union does not survive
// exactOptionalPropertyTypes, and these four fields are all the page reads.
interface RawOption {
  type: number;
  name: string;
  description: string;
  required?: boolean | undefined;
  options?: readonly RawOption[] | undefined;
}

interface RawCommand {
  name: string;
  description: string;
  default_member_permissions?: string | null | undefined;
  options?: readonly RawOption[] | undefined;
}

export interface CommandArg {
  name: string;
  required: boolean;
}

export interface CommandEntry {
  usage: string;
  description: string;
  args: CommandArg[];
  module: string;
  permission: string | null;
}

// Names and arity only. Discord prints each argument's own description while you type it, and
// carrying 111 commands' worth of them would double a page that already ships every command.
function argsOf(options: readonly RawOption[] | undefined): CommandArg[] {
  return (options ?? [])
    .filter((option) => option.type !== SUB_COMMAND && option.type !== SUB_COMMAND_GROUP)
    .map((option) => ({
      name: option.name,
      required: Boolean(option.required),
    }));
}

// Discord names its permissions in PascalCase; the consent screen and the server settings both
// print them spaced, which is the spelling an admin is looking for.
function spaced(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1 $2');
}

function permissionOf(data: RawCommand): string | null {
  const mask = data.default_member_permissions;
  if (!mask || mask === '0') return null;

  const names = permissionNames(BigInt(mask)).map(spaced);

  return names.length > 0 ? names.join(', ') : null;
}

function expand(moduleId: string, data: RawCommand) {
  const permission = permissionOf(data);
  const entries: CommandEntry[] = [];

  const push = (usage: string, description: string, options?: readonly RawOption[]) =>
    entries.push({ usage, description, args: argsOf(options), module: moduleId, permission });

  for (const option of data.options ?? []) {
    if (option.type === SUB_COMMAND) {
      push(`/${data.name} ${option.name}`, option.description, option.options);
    } else if (option.type === SUB_COMMAND_GROUP) {
      for (const nested of option.options ?? []) {
        push(`/${data.name} ${option.name} ${nested.name}`, nested.description, nested.options);
      }
    }
  }

  // A command whose options are all plain arguments is itself the runnable thing; one that only
  // holds subcommands is not, and listing it would put a line on the page nobody can type.
  if (entries.length === 0) push(`/${data.name}`, data.description, data.options);

  return entries;
}

export function collect(): CommandEntry[] {
  return MODULES.flatMap((manifest) =>
    (manifest.commands ?? []).flatMap((command) => expand(manifest.id, command.data as RawCommand)),
  ).sort((a, b) => a.usage.localeCompare(b.usage));
}

function lit(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

function render(entry: CommandEntry): string {
  const args = entry.args
    .map((arg) => `      { name: ${lit(arg.name)}, required: ${arg.required} },`)
    .join('\n');

  return [
    '  {',
    `    usage: ${lit(entry.usage)},`,
    `    description: ${lit(entry.description)},`,
    entry.args.length > 0 ? `    args: [\n${args}\n    ],` : '    args: [],',
    `    module: ${lit(entry.module)},`,
    `    permission: ${entry.permission === null ? 'null' : lit(entry.permission)},`,
    '  },',
  ].join('\n');
}

export function generate(): string {
  return `// Generated by scripts/build-commands.ts from the module manifests. Do not edit by hand.
// Re-run with \`bun run build:commands\` after changing any module's commands.

export interface CommandArg {
  name: string;
  required: boolean;
}

export interface CommandEntry {
  usage: string;
  description: string;
  args: readonly CommandArg[];
  module: string;
  permission: string | null;
}

export const COMMAND_SET: readonly CommandEntry[] = [
${collect().map(render).join('\n')}
];
`;
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, generate(), 'utf8');
  console.log(`wrote ${collect().length} commands to ${GENERATED_PATH}`);
}
