import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { MODULE_ICON_NAMES, RECORD_ICON_NAMES } from '../src/lib/modules/catalogue.ts';

const ROOT = join(import.meta.dir, '..');
const SRC = join(ROOT, 'src');

// Resolved, not joined onto node_modules: bun links workspace dependencies from a content store.
const require = createRequire(import.meta.url);
const ASSETS = join(dirname(require.resolve('@phosphor-icons/core/package.json')), 'assets');

export const GENERATED_PATH = join(SRC, 'components', 'ui', 'icon-set.gen.ts');

const WEIGHTS = ['regular', 'fill'] as const;

function sourceFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);

    if (entry.isDirectory()) sourceFiles(full, out);
    else if (/\.tsx?$/.test(entry.name) && !entry.name.endsWith('.gen.ts')) out.push(full);
  }

  return out;
}

export function renderableNames(): string[] {
  const names = new Set<string>([...MODULE_ICON_NAMES, ...RECORD_ICON_NAMES]);

  for (const file of sourceFiles(SRC)) {
    if (file === GENERATED_PATH) continue;

    const source = readFileSync(file, 'utf8');

    for (const tag of source.matchAll(/<Icon\b[\s\S]*?\/>/g)) {
      const prop = /name=(\{[\s\S]*?\}|"[a-z0-9-]+")/.exec(tag[0]);
      if (!prop?.[1]) throw new Error(`an <Icon> in ${file} has no name prop this can read`);

      const expression = prop[1];

      if (expression.startsWith('"')) {
        names.add(expression.slice(1, -1));
        continue;
      }

      // Drop the compared value in name={sort === 'asc' ? 'sort-ascending' : 'sort-descending'}.
      const branches = expression
        .replace(/[=!]==?\s*'[a-z0-9-]+'/g, '')
        .replace(/'[a-z0-9-]+'\s*[=!]==?/g, '');

      for (const literal of branches.matchAll(/'([a-z0-9-]+)'/g)) names.add(literal[1] ?? '');
    }

    for (const entry of source.matchAll(
      /\b(?:icon|trailingIcon|glyph)=(?:"([a-z0-9-]+)"|\{'([a-z0-9-]+)'\})/g,
    )) {
      names.add(entry[1] ?? entry[2] ?? '');
    }

    for (const entry of source.matchAll(/\b(?:icon|glyph):\s*'([a-z0-9-]+)'/g)) {
      names.add(entry[1] ?? '');
    }

    for (const table of source.matchAll(
      /:\s*(?:readonly\s+)?(?:Record<[^>]*?,\s*IconName>|IconName\[\])\s*=\s*([[{][\s\S]*?^\s*[\]}])/gm,
    )) {
      for (const literal of (table[1] ?? '').matchAll(/'([a-z0-9-]+)'/g))
        names.add(literal[1] ?? '');
    }
  }

  return [...names].filter(Boolean).sort();
}

function glyph(name: string, weight: (typeof WEIGHTS)[number]): string[] {
  const file = join(ASSETS, weight, weight === 'fill' ? `${name}-fill.svg` : `${name}.svg`);

  let svg: string;
  try {
    svg = readFileSync(file, 'utf8');
  } catch {
    throw new Error(
      `Phosphor has no '${name}' in ${weight}. Check the spelling against ${ASSETS}.`,
    );
  }

  const paths = [...svg.matchAll(/<path d="([^"]+)"\s*\/>/g)].map((match) => match[1] ?? '');

  if (paths.length === 0) throw new Error(`${file} has no <path> this generator can read`);

  return paths;
}

export function generate(): string {
  const body = renderableNames()
    .map((name) => {
      const weights = WEIGHTS.map(
        (w) =>
          `    ${w}: [${glyph(name, w)
            .map((d) => `'${d}'`)
            .join(', ')}],`,
      ).join('\n');

      return `  '${name}': {\n${weights}\n  },`;
    })
    .join('\n');

  const header = [
    '// Generated by scripts/build-icons.ts from @phosphor-icons/core. Do not edit by hand.',
    '// Re-run with `bun run build:icons` after adding an <Icon name> or a catalogue entry.',
  ].join('\n');

  return [
    header,
    '',
    `export const ICONS = {\n${body}\n} as const;`,
    '',
    'export type IconName = keyof typeof ICONS;',
    "export type IconWeight = 'regular' | 'fill';",
    '',
  ].join('\n');
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, generate(), 'utf8');

  console.log(
    `wrote ${renderableNames().length} icons in ${WEIGHTS.length} weights to ${GENERATED_PATH}`,
  );
}
