import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MODULES } from '../src/lib/modules/catalogue.ts';

const ROOT = join(import.meta.dir, '..');
const PAGES_DIR = join(ROOT, 'src', 'pages');

export const GENERATED_PATH = join(ROOT, 'src', 'components', 'module', 'registry.ts');

export function builtModules(): string[] {
  const known = new Set(MODULES.map((module) => module.id));

  return readdirSync(PAGES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith('.tsx'))
    .map((entry) => entry.name.replace(/\.tsx$/, ''))
    .filter((id) => known.has(id))
    .sort();
}

export function generate(): string {
  const ids = builtModules();

  const entries = ids.map((id) => `  ${id}: () => import('../../pages/${id}.tsx'),`).join('\n');

  const missing = MODULES.map((module) => module.id).filter((id) => !ids.includes(id));

  const note =
    missing.length === 0
      ? ' * Every module has one.'
      : ` * Still missing a page: ${missing.join(', ')}.`;

  return `// Generated by scripts/build-registry.ts from the files in src/pages. Do not edit by hand.
// Re-run with \`bun run build:registry\` after adding a module page.

import type { ModuleSummary } from '@proton/core';
import type { ComponentType } from 'react';
import { lazy } from 'react';
import type { ModuleMeta } from '../../lib/modules/catalogue.ts';

export interface ModulePageProps {
  guildId: string;
  meta: ModuleMeta;
  summary: ModuleSummary | undefined;
  /** The resolved area, already defaulted to the module's first when the URL named none. */
  area: string;
}

export type ModulePage = ComponentType<ModulePageProps>;

/**
 * One lazy entry per module, so a settings page carries only its own module's schema into the
 * browser rather than all thirty.
${note}
 */
const PAGES: Record<string, () => Promise<{ default: ModulePage }>> = {
${entries}
};

const CACHE = new Map<string, ModulePage>();

export function modulePage(moduleId: string): ModulePage | null {
  const loader = PAGES[moduleId];
  if (!loader) return null;

  const held = CACHE.get(moduleId);
  if (held) return held;

  const component = lazy(loader);
  CACHE.set(moduleId, component);
  return component;
}

export function hasModulePage(moduleId: string): boolean {
  return PAGES[moduleId] !== undefined;
}
`;
}

if (import.meta.main) {
  writeFileSync(GENERATED_PATH, generate(), 'utf8');

  const ids = builtModules();
  const missing = MODULES.map((module) => module.id).filter((id) => !ids.includes(id));

  console.log(`registered ${ids.length}/${MODULES.length} module pages`);
  if (missing.length > 0) console.log(`still missing: ${missing.join(', ')}`);
}
