import { existsSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MODULES } from '../src/lib/modules/catalogue.ts';

const ROOT = join(import.meta.dir, '..');
const ROUTES = join(ROOT, 'src', 'routes', 'dashboard', '$guildId');
const PAGES = join(ROOT, 'src', 'pages');

const WITH_PAGES = MODULES.filter((module) => !module.switchOnly);

const HEADER = [
  '// Generated by scripts/build-routes.ts. Do not edit by hand.',
  '// Re-run with `bun run build:routes` after adding a module to the catalogue.',
].join('\n');

function file(moduleId: string): string {
  return `${HEADER}

import { createFileRoute } from '@tanstack/react-router';
import { zodValidator } from '@tanstack/zod-adapter';
import { ModulePending } from '../../../components/module/pending.tsx';
import { ModuleRoute, moduleSearchSchema } from '../../../components/module/route.tsx';
import { loadModule } from '../../../lib/modules/preload.ts';
import Page from '../../../pages/${moduleId}.tsx';

export const Route = createFileRoute('/dashboard/$guildId/${moduleId}')({
  loader: ({ context, params, preload, location }) =>
    loadModule(context.queryClient, params.guildId, '${moduleId}', preload, location.search),
  validateSearch: zodValidator(moduleSearchSchema),
  // 0, not 1000 and 500: a click waiting on the page or its settings shows this header at once.
  pendingMs: 0,
  pendingMinMs: 0,
  pendingComponent: () => <ModulePending moduleId="${moduleId}" />,
  component: () => <ModuleRoute moduleId="${moduleId}" page={Page} />,
});
`;
}

export function generate(): { written: string[]; missing: string[] } {
  const written: string[] = [];
  const missing: string[] = [];

  for (const module of WITH_PAGES) {
    if (!existsSync(join(PAGES, `${module.id}.tsx`))) {
      missing.push(module.id);
      continue;
    }

    writeFileSync(join(ROUTES, `${module.id}.tsx`), file(module.id), 'utf8');
    written.push(module.id);
  }

  return { written, missing };
}

if (import.meta.main) {
  const { written, missing } = generate();

  // A module dropped from the catalogue or made switch-only leaves a route that still resolves.
  const known = new Set(WITH_PAGES.map((module) => module.id));
  const stale = readdirSync(ROUTES)
    .filter((name) => name.endsWith('.tsx'))
    .map((name) => name.replace(/\.tsx$/, ''))
    .filter((name) => name !== 'index' && !name.startsWith('$') && !known.has(name));

  for (const name of stale) unlinkSync(join(ROUTES, `${name}.tsx`));

  console.log(`wrote ${written.length} module routes`);
  if (missing.length > 0) console.log(`no page yet: ${missing.join(', ')}`);
  if (stale.length > 0) console.log(`removed stale: ${stale.join(', ')}`);
}
