// Generated by scripts/build-commands.ts from the module manifests. Do not edit by hand.
// Re-run with `bun run build:commands` after changing any module's commands.

export interface CommandArg {
  name: string;
  required: boolean;
}

export interface CommandEntry {
  usage: string;
  description: string;
  args: readonly CommandArg[];
  module: string;
  permission: string | null;
}

export const COMMAND_SET: readonly CommandEntry[] = [
  {
    usage: '/achievement reset',
    description: 'Reset a member’s progress and badges. Needs Manage Server.',
    args: [
      { name: 'member', required: true },
      { name: 'achievement', required: false },
      { name: 'rewards_again', required: false },
    ],
    module: 'achievements',
    permission: null,
  },
  {
    usage: '/achievement view',
    description: 'Show what an achievement takes, its tiers and rewards, and a member’s progress.',
    args: [
      { name: 'achievement', required: true },
      { name: 'user', required: false },
    ],
    module: 'achievements',
    permission: null,
  },
  {
    usage: '/achievements',
    description: 'Show a member’s achievement badges and their progress towards the rest.',
    args: [
      { name: 'user', required: false },
    ],
    module: 'achievements',
    permission: null,
  },
  {
    usage: '/afk clear',
    description: 'Clear your AFK, or with Manage Nicknames, someone else’s.',
    args: [
      { name: 'member', required: false },
    ],
    module: 'afk',
    permission: null,
  },
  {
    usage: '/afk set',
    description: 'Mark yourself AFK in this server.',
    args: [
      { name: 'reason', required: false },
    ],
    module: 'afk',
    permission: null,
  },
  {
    usage: '/antinuke maintenance',
    description: 'Pause Anti-Nuke for a set time while you make bulk changes.',
    args: [
      { name: 'duration', required: true },
      { name: 'reason', required: false },
    ],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/antinuke resume',
    description: 'End maintenance mode now and re-arm Anti-Nuke.',
    args: [],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/antinuke status',
    description: 'Show whether Anti-Nuke is armed, and its limits.',
    args: [],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/applications queue',
    description: 'See how many applications are waiting for review.',
    args: [],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/applications view',
    description: 'Open an application by its number.',
    args: [
      { name: 'number', required: true },
    ],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/apply resume',
    description: 'Continue an application you saved for later.',
    args: [],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/apply start',
    description: 'See what a form asks and whether you can apply, then start or continue.',
    args: [
      { name: 'form', required: true },
    ],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/apply status',
    description: 'See your applications in this server and their status.',
    args: [],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/apply withdraw',
    description: 'Withdraw an application that hasn’t been decided yet.',
    args: [
      { name: 'application', required: true },
    ],
    module: 'applications',
    permission: null,
  },
  {
    usage: '/backup create',
    description: 'Take a snapshot of every channel, role and channel permission.',
    args: [],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/backup list',
    description: 'Show the snapshots this server has kept.',
    args: [],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/backup restore',
    description: 'Recreate the missing channels and roles from a snapshot.',
    args: [
      { name: 'backup_id', required: true },
      { name: 'confirm', required: false },
    ],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/ban add',
    description: 'Ban a member from this server.',
    args: [
      { name: 'user', required: true },
      { name: 'duration', required: false },
      { name: 'delete_message_days', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Ban Members',
  },
  {
    usage: '/ban remove',
    description: 'Lift a ban on a user.',
    args: [
      { name: 'user_id', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Ban Members',
  },
  {
    usage: '/branding',
    description: 'Re-apply Proton’s nickname and profile in this server and see what Discord accepted.',
    args: [],
    module: 'branding',
    permission: 'Manage Server',
  },
  {
    usage: '/counters refresh',
    description: 'Update every counter channel now, without waiting for the next refresh.',
    args: [],
    module: 'counters',
    permission: 'Manage Channels',
  },
  {
    usage: '/giveaway blacklist add',
    description: 'Block a member from entering giveaways.',
    args: [
      { name: 'member', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway blacklist list',
    description: 'Show who can’t enter giveaways in this server.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway blacklist remove',
    description: 'Let a blocked member enter giveaways again.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus add',
    description: 'Give a member extra entries.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: true },
      { name: 'entries', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus list',
    description: 'Show who has been given extra entries.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus remove',
    description: 'Take back all the extra entries a member was given.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway cancel',
    description: 'Stop a giveaway without drawing any winners.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway create',
    description: 'Build a giveaway step by step, with requirements and bonus entries.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway drop',
    description: 'Post a drop. The first eligible member to press it wins, with no draw.',
    args: [
      { name: 'prize', required: true },
      { name: 'expires', required: false },
      { name: 'description', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway edit',
    description: 'Change a giveaway that’s already posted.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'prize', required: false },
      { name: 'description', required: false },
      { name: 'winners', required: false },
      { name: 'image', required: false },
      { name: 'colour', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway end',
    description: 'Draw a running giveaway now, before its deadline.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway entrants',
    description: 'List everyone in a giveaway and how many entries they have.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'page', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway entries',
    description: 'Show the top entrants in a giveaway, or how many entries a member has.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway export',
    description: 'Download the entrant list as a CSV file.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway extend',
    description: 'Give a giveaway more time.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'duration', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway history',
    description: 'Show everything that has happened to a giveaway, in order.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway info',
    description: 'Show the details of a giveaway.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway list',
    description: 'Show the giveaways running in this server.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway pause',
    description: 'Close entries for now. The time left is kept until you resume it.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway reroll',
    description: 'Draw new winners for a giveaway that already ended.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'count', required: false },
      { name: 'allow-repeat', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway resume',
    description: 'Reopen a paused giveaway. Its end time moves by however long it was paused.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway shorten',
    description: 'Make a giveaway end sooner.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'duration', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway start',
    description: 'Post a giveaway in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'prize', required: true },
      { name: 'winners', required: false },
      { name: 'description', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway stats',
    description: 'Show giveaway totals for this server.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template delete',
    description: 'Delete a saved template.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template list',
    description: 'Show this server’s saved templates.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template load',
    description: 'Start a giveaway from a saved template.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template save',
    description: 'Save a finished or running giveaway as a template.',
    args: [
      { name: 'name', required: true },
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/help',
    description: 'What Proton does, and where to configure it.',
    args: [],
    module: 'help',
    permission: null,
  },
  {
    usage: '/kick',
    description: 'Remove a member from this server.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Kick Members',
  },
  {
    usage: '/leaderboard',
    description: 'Show this server’s XP leaderboard.',
    args: [
      { name: 'page', required: false },
    ],
    module: 'leveling',
    permission: null,
  },
  {
    usage: '/lockdown add',
    description: 'Stop everyone from posting in this channel.',
    args: [
      { name: 'duration', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/lockdown remove',
    description: 'Let everyone post in this channel again.',
    args: [
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/message list',
    description: 'List this server’s templates.',
    args: [],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/message post',
    description: 'Post a template.',
    args: [
      { name: 'name', required: true },
      { name: 'channel', required: false },
    ],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/message send',
    description: 'Compose a one-off embed and post it in this channel.',
    args: [],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/phishing',
    description: 'Check the phishing blocklist and how this server handles a match.',
    args: [],
    module: 'phishing',
    permission: 'Manage Server',
  },
  {
    usage: '/ping',
    description: 'Check that Proton is responding.',
    args: [],
    module: 'ping',
    permission: null,
  },
  {
    usage: '/poll create',
    description: 'Post a poll in this channel.',
    args: [
      { name: 'question', required: true },
      { name: 'answers', required: true },
      { name: 'duration_hours', required: false },
      { name: 'multiple', required: false },
    ],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/poll end',
    description: 'Close one of Proton’s polls early.',
    args: [
      { name: 'message_id', required: true },
    ],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/poll list',
    description: 'Show the polls running in this server.',
    args: [],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/quarantine add',
    description: 'Replace a member’s roles with the quarantine role, saving the ones they had.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'verification',
    permission: 'Manage Roles',
  },
  {
    usage: '/quarantine remove',
    description: 'Release a member from quarantine and give back the roles they had.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'verification',
    permission: 'Manage Roles',
  },
  {
    usage: '/rank',
    description: 'Show a member’s level, XP and place on the leaderboard.',
    args: [
      { name: 'user', required: false },
    ],
    module: 'leveling',
    permission: null,
  },
  {
    usage: '/remind',
    description: 'Remind yourself about something later, in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'text', required: true },
    ],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/reminders cancel',
    description: 'Cancel one of your reminders.',
    args: [
      { name: 'reminder', required: true },
    ],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/reminders list',
    description: 'Show the reminders you have waiting in this server.',
    args: [],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/report',
    description: 'Report a member to this server’s staff.',
    args: [
      { name: 'member', required: true },
      { name: 'message', required: false },
      { name: 'evidence', required: false },
    ],
    module: 'moderation',
    permission: null,
  },
  {
    usage: '/role add',
    description: 'Add a role to a member.',
    args: [
      { name: 'user', required: true },
      { name: 'role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role all',
    description: 'Add a role to every member.',
    args: [
      { name: 'role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role bots',
    description: 'Add a role to every bot.',
    args: [
      { name: 'role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role cancel',
    description: 'Stop a mass role change that’s still running.',
    args: [],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role humans',
    description: 'Add a role to every member except bots.',
    args: [
      { name: 'role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role in',
    description: 'Add a role to every member who has another role.',
    args: [
      { name: 'role', required: true },
      { name: 'target_role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/role remove',
    description: 'Remove a role from a member.',
    args: [
      { name: 'user', required: true },
      { name: 'role', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Roles, Timeout Members',
  },
  {
    usage: '/rolemenu',
    description: 'Post a role menu, or update one that’s already posted.',
    args: [
      { name: 'menu', required: true },
      { name: 'message', required: false },
    ],
    module: 'rolemenu',
    permission: 'Manage Roles',
  },
  {
    usage: '/slowmode',
    description: 'Set how often members may post in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/suggest',
    description: 'Post a suggestion for the server to vote on.',
    args: [
      { name: 'text', required: true },
    ],
    module: 'suggestions',
    permission: null,
  },
  {
    usage: '/suggestion accept',
    description: 'Accept a suggestion and update its post.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/suggestion deny',
    description: 'Deny a suggestion and update its post.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/suggestion implement',
    description: 'Mark a suggestion as implemented and update its post.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/tag',
    description: 'Post a saved snippet.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags create',
    description: 'Save a new snippet.',
    args: [
      { name: 'name', required: true },
      { name: 'content', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags delete',
    description: 'Delete a tag.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags edit',
    description: 'Replace what an existing tag posts.',
    args: [
      { name: 'name', required: true },
      { name: 'content', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags info',
    description: 'Show who created a tag and how often it’s been posted.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags list',
    description: 'List this server’s tags.',
    args: [
      { name: 'page', required: false },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/ticket add',
    description: 'Give a member access to this ticket.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket assign',
    description: 'Assign this ticket to a staff member.',
    args: [
      { name: 'user', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist add',
    description: 'Block a member from opening tickets.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
      { name: 'duration', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist list',
    description: 'List members who can’t open tickets.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist remove',
    description: 'Let a member open tickets again.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket claim',
    description: 'Claim this ticket.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket close',
    description: 'Close this ticket, or another one by its number.',
    args: [
      { name: 'reason', required: false },
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket create',
    description: 'Open a ticket without using a panel.',
    args: [
      { name: 'type', required: true },
      { name: 'subject', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket delete',
    description: 'Delete a ticket and its channel for good.',
    args: [
      { name: 'number', required: false },
      { name: 'reason', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket info',
    description: 'Show a ticket’s details.',
    args: [
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket list',
    description: 'List open tickets. Members see only their own.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket lock',
    description: 'Let only staff post in this ticket, without closing it.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket move',
    description: 'Move this ticket to another category.',
    args: [
      { name: 'category', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket panel',
    description: 'Post a ticket panel so members can open tickets from it.',
    args: [
      { name: 'panel', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket priority',
    description: 'Change this ticket’s priority.',
    args: [
      { name: 'level', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket remove',
    description: 'Remove a member’s access to this ticket.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket rename',
    description: 'Rename this ticket’s channel.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket reopen',
    description: 'Reopen a closed ticket.',
    args: [
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket response',
    description: 'Post a quick response in this ticket.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket stats',
    description: 'Show ticket stats for this server.',
    args: [
      { name: 'days', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket transcript',
    description: 'Get a transcript of this ticket so far.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket transfer',
    description: 'Give ownership of this ticket to another member.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket unclaim',
    description: 'Unclaim this ticket so other staff can take it.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket unlock',
    description: 'Let members post in this ticket again.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/timeout add',
    description: 'Time a member out for a while.',
    args: [
      { name: 'user', required: true },
      { name: 'duration', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/timeout remove',
    description: 'End a timeout early.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/verify',
    description: 'Verify yourself and get access to this server.',
    args: [],
    module: 'verification',
    permission: null,
  },
  {
    usage: '/voice block',
    description: 'Keep a member out, and disconnect them if they’re in.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice claim',
    description: 'Take over a channel whose owner has left.',
    args: [],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice delete',
    description: 'Delete your channel now.',
    args: [],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice invite',
    description: 'Give a member access to your channel so you can invite them.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice kick',
    description: 'Disconnect a member from your channel.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice limit',
    description: 'Set how many members can join your channel.',
    args: [
      { name: 'limit', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice privacy',
    description: 'Choose who can join your channel.',
    args: [
      { name: 'mode', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice region',
    description: 'Set your channel’s voice region, or let Discord choose.',
    args: [
      { name: 'region', required: false },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice rename',
    description: 'Rename your channel.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice transfer',
    description: 'Make another member the owner of your channel.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice trust',
    description: 'Let a member join, even when your channel is locked or private.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice unblock',
    description: 'Unblock a member.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice untrust',
    description: 'Stop trusting a member.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/warn add',
    description: 'Record a warning against a member.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/warn remove',
    description: 'Withdraw a warning, so it stops counting against the member.',
    args: [
      { name: 'case', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/xp event end',
    description: 'End every XP event running now.',
    args: [],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp event list',
    description: 'List the running and scheduled XP events.',
    args: [],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp event start',
    description: 'Start or schedule an XP event.',
    args: [
      { name: 'multiplier', required: true },
      { name: 'duration', required: true },
      { name: 'starts_in', required: false },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp give',
    description: 'Add XP to a member’s total.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp set',
    description: 'Set a member’s total to an exact amount.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp take',
    description: 'Remove XP from a member’s total.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: 'Apps › Punish author',
    description: 'Punish the author of a message, keeping the message as proof.',
    args: [],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: 'Apps › Report message',
    description: 'Report a message to this server’s staff.',
    args: [],
    module: 'moderation',
    permission: null,
  },
  {
    usage: 'Apps › Report user',
    description: 'Report a member to this server’s staff.',
    args: [],
    module: 'moderation',
    permission: null,
  },
];
