// Generated by scripts/build-commands.ts from the module manifests. Do not edit by hand.
// Re-run with `bun run build:commands` after changing any module's commands.

export interface CommandArg {
  name: string;
  required: boolean;
}

export interface CommandEntry {
  usage: string;
  description: string;
  args: readonly CommandArg[];
  module: string;
  permission: string | null;
}

export const COMMAND_SET: readonly CommandEntry[] = [
  {
    usage: '/antinuke maintenance',
    description: 'Suspend the breaker for a fixed period of bulk admin work.',
    args: [
      { name: 'duration', required: true },
      { name: 'reason', required: false },
    ],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/antinuke resume',
    description: 'End maintenance mode now and re-arm the breaker.',
    args: [],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/antinuke status',
    description: 'Show whether the breaker is armed, and at what thresholds.',
    args: [],
    module: 'antinuke',
    permission: 'Manage Server',
  },
  {
    usage: '/backup create',
    description: 'Take a snapshot of every channel, role and permission overwrite.',
    args: [],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/backup list',
    description: 'Show the snapshots this server has kept.',
    args: [],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/backup restore',
    description: 'Recreate the channels and roles from a snapshot.',
    args: [
      { name: 'backup_id', required: true },
      { name: 'confirm', required: false },
    ],
    module: 'backup',
    permission: 'Manage Server',
  },
  {
    usage: '/ban add',
    description: 'Ban a member from this server.',
    args: [
      { name: 'user', required: true },
      { name: 'duration', required: false },
      { name: 'delete_message_days', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Ban Members',
  },
  {
    usage: '/ban remove',
    description: 'Lift a ban on a user.',
    args: [
      { name: 'user_id', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Ban Members',
  },
  {
    usage: '/counters refresh',
    description: 'Update every counter channel now instead of waiting for the timer.',
    args: [],
    module: 'counters',
    permission: 'Manage Channels',
  },
  {
    usage: '/giveaway blacklist add',
    description: 'Block a member from entering giveaways.',
    args: [
      { name: 'member', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway blacklist list',
    description: 'Show who cannot enter giveaways here.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway blacklist remove',
    description: 'Let a blocked member enter giveaways again.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus add',
    description: 'Give a member extra entries.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: true },
      { name: 'entries', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus list',
    description: 'Show who has been granted extra entries.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway bonus remove',
    description: 'Take back every extra entry a member was granted.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway cancel',
    description: 'Stop a running giveaway without drawing anybody.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway create',
    description: 'Build a giveaway step by step, with requirements and bonus entries.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway drop',
    description: 'Post a drop — the first eligible member to press it wins, with no draw.',
    args: [
      { name: 'prize', required: true },
      { name: 'expires', required: false },
      { name: 'description', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway edit',
    description: 'Change a giveaway that is already posted.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'prize', required: false },
      { name: 'description', required: false },
      { name: 'winners', required: false },
      { name: 'image', required: false },
      { name: 'colour', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway end',
    description: 'Draw a running giveaway now, before its deadline.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway entrants',
    description: 'Page through everybody in a giveaway and how many entries they hold.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'page', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway entries',
    description: 'Show how many entries somebody has, and why.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'member', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway export',
    description: 'Download the entrant list as a CSV, for an audit.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway extend',
    description: 'Give a giveaway more time.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'duration', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway history',
    description: 'Everything that has happened to one giveaway, in order.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway info',
    description: 'Everything about one giveaway.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway list',
    description: 'Show the giveaways running in this server.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway pause',
    description: 'Close entries without ending it. The time left is held where it is.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'reason', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway reroll',
    description: 'Draw new winners for a giveaway that already ended.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'count', required: false },
      { name: 'allow-repeat', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway resume',
    description: 'Reopen a paused giveaway. The deadline moves by the time it was paused.',
    args: [
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway shorten',
    description: 'Bring a giveaway’s deadline forward.',
    args: [
      { name: 'giveaway', required: true },
      { name: 'duration', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway start',
    description: 'Post a giveaway in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'prize', required: true },
      { name: 'winners', required: false },
      { name: 'description', required: false },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway stats',
    description: 'Giveaway totals for this server.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template delete',
    description: 'Delete a saved template.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template list',
    description: 'Show this server’s saved templates.',
    args: [],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template load',
    description: 'Start a giveaway from a saved template.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/giveaway template save',
    description: 'Save a finished or running giveaway as a template.',
    args: [
      { name: 'name', required: true },
      { name: 'giveaway', required: true },
    ],
    module: 'giveaways',
    permission: null,
  },
  {
    usage: '/help',
    description: 'What Proton does, and where to configure it.',
    args: [],
    module: 'help',
    permission: null,
  },
  {
    usage: '/kick',
    description: 'Remove a member from this server.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Kick Members',
  },
  {
    usage: '/leaderboard',
    description: 'Show this server’s XP leaderboard.',
    args: [
      { name: 'page', required: false },
    ],
    module: 'leveling',
    permission: null,
  },
  {
    usage: '/lockdown',
    description: 'Stop everyone posting in this channel.',
    args: [
      { name: 'duration', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/message list',
    description: 'List this server’s saved messages.',
    args: [],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/message post',
    description: 'Post a saved message.',
    args: [
      { name: 'name', required: true },
      { name: 'channel', required: false },
    ],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/message send',
    description: 'Compose a one-off message and post it here.',
    args: [],
    module: 'messages',
    permission: 'Manage Messages',
  },
  {
    usage: '/phishing',
    description: 'Show the state of the phishing blocklist in this server.',
    args: [],
    module: 'phishing',
    permission: 'Manage Server',
  },
  {
    usage: '/ping',
    description: 'Check that Proton is responding.',
    args: [],
    module: 'ping',
    permission: null,
  },
  {
    usage: '/poll create',
    description: 'Post a poll in this channel.',
    args: [
      { name: 'question', required: true },
      { name: 'answers', required: true },
      { name: 'duration_hours', required: false },
      { name: 'multiple', required: false },
    ],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/poll end',
    description: 'Close one of Proton’s polls before its clock runs out.',
    args: [
      { name: 'message_id', required: true },
    ],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/poll list',
    description: 'Show the polls running in this server.',
    args: [],
    module: 'polls',
    permission: null,
  },
  {
    usage: '/quarantine',
    description: 'Swap a member’s roles for the quarantine role, recording what they had.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'verification',
    permission: 'Manage Roles',
  },
  {
    usage: '/rank',
    description: 'Show a member’s level, XP and place on the leaderboard.',
    args: [
      { name: 'user', required: false },
    ],
    module: 'leveling',
    permission: null,
  },
  {
    usage: '/remind',
    description: 'Have Proton remind you about something later, in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'text', required: true },
    ],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/reminders cancel',
    description: 'Cancel one of your reminders.',
    args: [
      { name: 'reminder', required: true },
    ],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/reminders list',
    description: 'Show the reminders you have waiting in this server.',
    args: [],
    module: 'reminders',
    permission: null,
  },
  {
    usage: '/rolemenu',
    description: 'Post one of this server’s role menus, or refresh it after editing it.',
    args: [
      { name: 'menu', required: true },
      { name: 'message', required: false },
    ],
    module: 'rolemenu',
    permission: 'Manage Roles',
  },
  {
    usage: '/slowmode',
    description: 'Set how often members may post in this channel.',
    args: [
      { name: 'duration', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/suggest',
    description: 'Suggest something to this server’s staff.',
    args: [
      { name: 'text', required: true },
    ],
    module: 'suggestions',
    permission: null,
  },
  {
    usage: '/suggestion accept',
    description: 'Accept a suggestion and edit its post to say so.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/suggestion deny',
    description: 'Turn a suggestion down and edit its post to say so.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/suggestion implement',
    description: 'Mark a suggestion as done and edit its post to say so.',
    args: [
      { name: 'number', required: true },
      { name: 'reason', required: false },
    ],
    module: 'suggestions',
    permission: 'Manage Messages',
  },
  {
    usage: '/tag',
    description: 'Post a saved snippet.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags create',
    description: 'Save a new snippet.',
    args: [
      { name: 'name', required: true },
      { name: 'content', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags delete',
    description: 'Remove a tag.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags edit',
    description: 'Replace what an existing tag posts.',
    args: [
      { name: 'name', required: true },
      { name: 'content', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags info',
    description: 'Show who wrote a tag and how often it is used.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/tags list',
    description: 'List this server’s tags.',
    args: [
      { name: 'page', required: false },
    ],
    module: 'tags',
    permission: null,
  },
  {
    usage: '/ticket add',
    description: 'Give somebody access to this ticket.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket assign',
    description: 'Assign this ticket to a staff member.',
    args: [
      { name: 'user', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist add',
    description: 'Stop a member opening tickets.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
      { name: 'duration', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist list',
    description: 'Show who cannot open tickets.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket blacklist remove',
    description: 'Let a member open tickets again.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket claim',
    description: 'Take this ticket.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket close',
    description: 'Close the ticket you are in, or any ticket by its number.',
    args: [
      { name: 'reason', required: false },
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket create',
    description: 'Open a ticket without using a panel.',
    args: [
      { name: 'type', required: true },
      { name: 'subject', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket delete',
    description: 'Delete a ticket and its channel for good.',
    args: [
      { name: 'number', required: false },
      { name: 'reason', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket info',
    description: 'Show everything Proton knows about a ticket.',
    args: [
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket list',
    description: 'List the tickets that are currently open.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket lock',
    description: 'Stop the member posting without closing the ticket.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket move',
    description: 'Move this ticket into another category.',
    args: [
      { name: 'category', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket panel',
    description: 'Post a ticket panel so members can open tickets from it.',
    args: [
      { name: 'panel', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket priority',
    description: 'Change how urgent this ticket is.',
    args: [
      { name: 'level', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket remove',
    description: 'Take somebody’s access to this ticket away.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket rename',
    description: 'Rename this ticket’s channel.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket reopen',
    description: 'Reopen a closed ticket.',
    args: [
      { name: 'number', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket response',
    description: 'Post one of this server’s saved replies into the ticket.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket stats',
    description: 'Support statistics for this server.',
    args: [
      { name: 'days', required: false },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket transcript',
    description: 'Get a transcript of this ticket as it stands.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket transfer',
    description: 'Hand ownership of this ticket to somebody else.',
    args: [
      { name: 'user', required: true },
    ],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket unclaim',
    description: 'Let this ticket go.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/ticket unlock',
    description: 'Let the member post again.',
    args: [],
    module: 'tickets',
    permission: null,
  },
  {
    usage: '/timeout',
    description: 'Silence a member for a while.',
    args: [
      { name: 'user', required: true },
      { name: 'duration', required: false },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/unlock',
    description: 'Let everyone post in this channel again.',
    args: [
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Manage Channels',
  },
  {
    usage: '/unquarantine',
    description: 'Lift a quarantine and put the member’s roles back exactly.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'verification',
    permission: 'Manage Roles',
  },
  {
    usage: '/untimeout',
    description: 'End a timeout early.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/verify',
    description: 'Pass this server’s verification and get access.',
    args: [],
    module: 'verification',
    permission: null,
  },
  {
    usage: '/voice block',
    description: 'Keep somebody out, and disconnect them if they are inside.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice claim',
    description: 'Take over a channel whose owner has left.',
    args: [],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice delete',
    description: 'Delete your channel now.',
    args: [],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice invite',
    description: 'Send somebody a link to your channel.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice kick',
    description: 'Disconnect somebody from your channel.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice limit',
    description: 'Set how many members may join. 0 removes the limit.',
    args: [
      { name: 'limit', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice privacy',
    description: 'Choose who may join.',
    args: [
      { name: 'mode', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice region',
    description: 'Pin the voice region, or let Discord choose.',
    args: [
      { name: 'region', required: false },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice rename',
    description: 'Rename your channel.',
    args: [
      { name: 'name', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice transfer',
    description: 'Hand the channel to somebody else in it.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice trust',
    description: 'Let somebody join even when the channel is locked.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice unblock',
    description: 'Lift a block.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/voice untrust',
    description: 'Take back that trust.',
    args: [
      { name: 'member', required: true },
    ],
    module: 'tempvc',
    permission: null,
  },
  {
    usage: '/warn',
    description: 'Record a warning against a member.',
    args: [
      { name: 'user', required: true },
      { name: 'reason', required: false },
    ],
    module: 'moderation',
    permission: 'Timeout Members',
  },
  {
    usage: '/xp give',
    description: 'Add XP to a member’s total.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp set',
    description: 'Set a member’s total to an exact amount.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
  {
    usage: '/xp take',
    description: 'Remove XP from a member’s total.',
    args: [
      { name: 'user', required: true },
      { name: 'amount', required: true },
    ],
    module: 'leveling',
    permission: 'Manage Server',
  },
];
