export {
  collectConfigTemplates,
  formatTemplateIssues,
  type ModuleTemplates,
  type TemplateIssue,
  type TemplateReport,
  type TemplateSite,
  validateConfigTemplates,
} from './config-templates.ts';
export {
  createPlaceholderRegistry,
  definitionsFor,
  isForbiddenKey,
  isRestricted,
  type PlaceholderContext,
  type PlaceholderDefinition,
  PlaceholderDefinitionError,
  type PlaceholderDefinitionInput,
  type PlaceholderRegistry,
  type PlaceholderResolution,
  placeholderDefinitionSchema,
  unavailableReason,
} from './definitions.ts';
export {
  DIAGNOSTIC_CODES,
  DIAGNOSTIC_SEVERITIES,
  DIAGNOSTIC_SEVERITY,
  type DiagnosticCode,
  type DiagnosticSeverity,
  type Span,
  spanSchema,
  type TemplateDiagnostic,
  templateDiagnosticSchema,
} from './diagnostics.ts';
export {
  clipGraphemes,
  DISCORD_TEXT_LIMITS,
  enforceMessageLimits,
  type LimitCode,
  type LimitReport,
} from './discord-limits.ts';
export {
  escapeDiscordMarkdown,
  escapeTemplateText,
  isHttpUrl,
  normaliseChannelName,
} from './format.ts';
export {
  type ParsedTemplate,
  type PlaceholderToken,
  parseTemplate,
  type TemplateToken,
  type TextToken,
} from './grammar.ts';
export {
  BRACE_ESCAPE_HELP,
  CHANNEL_KINDS,
  CHANNEL_NAME_MAX,
  type ChannelKind,
  FIELD_LABELS,
  PLACEHOLDER_LIMITS,
  SENSITIVITIES,
  SENSITIVITY_LABELS,
  type Sensitivity,
  TEMPLATE_FIELDS,
  type TemplateField,
} from './limits.ts';
export {
  collectMessageSites,
  MESSAGE_TEMPLATE_FIELDS,
  type MentionSettings,
  type MessageRender,
  type MessageRenderOptions,
  type MessageSite,
  type PathDiagnostic,
  type ProtonMessageLike,
  REPLY_ACTION_FIELDS,
  renderMessageTemplate,
} from './message-fields.ts';
export {
  MODIFIER_NAMES,
  type ModifierArgument,
  type ModifierName,
  modifiersFor,
  modifierUsage,
  type ParsedModifier,
} from './modifiers.ts';
export {
  lookupFrom,
  type PlaceholderLookup,
  type PlaceholderRequest,
  type RenderOptions,
  type RenderResult,
  renderTemplate,
} from './render.ts';
export {
  SAMPLE_BOT,
  SAMPLE_CONTEXT,
  SAMPLE_GIVEAWAY_WIN,
  SAMPLE_IDS,
  SAMPLE_LEVEL_UP,
  SAMPLE_MEMBER,
  SAMPLE_NOW,
  SAMPLE_SERVER,
  SAMPLE_TEMPVC,
  SAMPLE_TICKET_CLOSED,
  SAMPLE_TICKET_OPEN,
  type SampleContext,
  type SampleId,
  type SampleMember,
} from './samples.ts';
export {
  type BotFacts,
  botDefinitions,
  buildBotValues,
  buildChannelValues,
  buildEventValues,
  buildServerValues,
  buildTimeValues,
  buildUserValues,
  CHANNEL_NAMESPACES,
  type ChannelFacts,
  type ChannelNamespace,
  channelDefinitions,
  countableChannels,
  type EventFacts,
  eventDefinitions,
  type GuildStateLike,
  guildBannerUrl,
  guildIconUrl,
  type MemberFacts,
  type PlaceholderEnvironment,
  PROTON_SUPPORT_URL,
  type ServerFacts,
  SHARED_PINGS,
  serverDefinitions,
  serverFactsFrom,
  timeDefinitions,
  USER_NAMESPACES,
  type UserFacts,
  type UserNamespace,
  userDefinitions,
  withAliases,
  withAvailability,
} from './shared/index.ts';
export {
  aliasFallbacks,
  aliasValues,
  type BuildEnv,
  definePlaceholderSurface,
  mentionsAny,
  type PingKind,
  type PlaceholderSurface,
  type PlaceholderSurfaceInput,
  SURFACE_DIAGNOSTIC_CODES,
  SURFACE_DIAGNOSTIC_SEVERITY,
  type SurfaceDiagnostic,
  type SurfaceDiagnosticCode,
  type SurfaceSample,
  suggestKey,
  surfaceDiagnosticSchema,
  type TemplateFieldSpec,
  usedKeys,
} from './surface.ts';
export { type ValidateOptions, type ValidationResult, validateTemplate } from './validate.ts';
export {
  ABSENT_STATES,
  type AbsentState,
  type AbsentValue,
  absentValueSchema,
  describeType,
  type FlowType,
  type ListValue,
  listValueSchema,
  type PlaceholderType,
  type PlaceholderValue,
  placeholderTypeSchema,
  placeholderValue,
  placeholderValueSchema,
  type ResolvedValue,
  resolvedValueSchema,
  SCALAR_TYPES,
  type ScalarType,
  type ScalarValue,
  scalarTypeSchema,
  scalarValueSchema,
  typeOf,
} from './values.ts';
