export {
  CASE_PAGE_SIZE_DEFAULT,
  CASE_PAGE_SIZE_MAX,
  CASE_SCOPES,
  CASE_SORT_DIRECTIONS,
  CASE_SORT_FIELDS,
  type CaseQuery,
  type CaseQueryInput,
  type CaseRecord,
  type CaseScope,
  type CaseSearchResult,
  type CaseSortDirection,
  type CaseSortField,
  caseQuerySchema,
} from './actions/case-query.ts';
export type { CaseInput, CaseRecorder } from './actions/case-recorder.ts';
export { DEDUPE_PREFIX, type DedupeStore, RedisDedupeStore } from './actions/dedupe.ts';
export {
  type ActionExecutorDeps,
  DefaultActionExecutor,
  REDACTED,
  redactSecrets,
} from './actions/executor.ts';
export {
  ACTION_KINDS,
  type ActionKind,
  exposesUpstreamOnFailure,
  isActionKind,
  isChannelScopedFor,
  isLedgerOnly,
  isNeverRecorded,
  isVoiceDisconnect,
  LEDGER_ONLY_KINDS,
  NEVER_RECORDED_KINDS,
  REQUIRED_PERMISSIONS,
  REVERSAL_OF,
  requiredPermissionsFor,
  reversalOf,
  TARGETS_MEMBER,
  targetsMember,
  UPSTREAM_ON_FAILURE_KINDS,
} from './actions/kinds.ts';
export * from './actions/payloads.ts';
export { type PrecheckInput, runPrechecks } from './actions/prechecks.ts';
export {
  type MemberRolesLookup,
  type ResolveContextDeps,
  type ResolveContextHints,
  type ResolveContextResult,
  resolvePrecheckContext,
} from './actions/resolve-context.ts';
export {
  HttpRestProxyClient,
  type RestFile,
  type RestProxyClient,
  type RestRequestOptions,
  type RestResponse,
  RestTimeoutError,
} from './actions/rest-client.ts';
export { type PayloadResult, type RestCall, toRestCall } from './actions/rest-mapping.ts';
export {
  AUTO_REVERSAL_ACTOR,
  type CaseReversalInput,
  type CaseReversalStore,
  isReversalIdempotencyKey,
  planReversal,
  type ReversalPlan,
  type ReversalPlanResult,
  reversalIdempotencyKey,
} from './actions/reversal.ts';
export {
  DatabaseReversalScheduler,
  type ReversalSchedulerDeps,
} from './actions/reversal-scheduler.ts';
export {
  ScheduledActionSweeper,
  type ScheduledActionSweeperDeps,
  type ScheduledModuleJob,
  type SweepResult,
  sweepClaimKey,
} from './actions/scheduled-action-sweeper.ts';
export {
  type ClaimDueOptions,
  type CompleteOutcome,
  MODULE_JOB_KIND,
  moduleScheduleKey,
  type ScheduledActionInput,
  type ScheduledActionPayload,
  type ScheduledActionRecord,
  type ScheduledActionStore,
  type ScheduledModulePayload,
  type ScheduledReversalPayload,
  type ScheduleOptions,
  type ScheduleOutcome,
  scheduledActionPayloadSchema,
  scheduledModulePayloadSchema,
  scheduledReversalPayloadSchema,
} from './actions/scheduled-actions.ts';
export {
  type ActionExecutor,
  type ActionFailure,
  type ActionRequest,
  type ActionResult,
  type ActionStatus,
  actionRequestSchema,
  isScopedActionExecutor,
  type ScopedActionExecutor,
} from './actions/types.ts';
export {
  APPEAL_LINK_PATH,
  APPEAL_LINK_TTL_MS,
  APPEAL_PANEL_ID_MAX,
  type AppealLinkClaims,
  type AppealLinkResult,
  appealLinkClaimsSchema,
  appealLinkUrl,
  type NewAppealLinkInput,
  newAppealLinkClaims,
  readAppealLink,
  signAppealLink,
} from './appeal-link.ts';
export {
  BLOCK_REASON_MAX,
  BLOCKED_PAGE_SIZE_DEFAULT,
  BLOCKED_PAGE_SIZE_MAX,
  BLOCKED_STATES,
  type BlockedEvidence,
  type BlockedMember,
  type BlockedMemberList,
  type BlockedMemberQuery,
  type BlockedMemberStore,
  type BlockedState,
  type BlockMemberInput,
  blockedEvidenceSchema,
  blockedMemberListSchema,
  blockedMemberQuerySchema,
  blockedMemberSchema,
  blockMemberInputSchema,
  type LiftBlockInput,
  type LiftBlockResult,
  liftBlockInputSchema,
  liftBlockResultSchema,
} from './blocked/query.ts';
export {
  type BrandingNameStyleStore,
  NAME_STYLE_OUTCOMES,
  NAME_STYLE_REASONS,
  type NameStyleAttempt,
  type NameStyleOutcome,
  type NameStyleReason,
  type NameStyleState,
  nameStyleAttemptSchema,
  nameStyleStateSchema,
} from './branding/name-style-state.ts';
export * from './commands/index.ts';
export {
  type BooleanField,
  type ChannelIdField,
  type ColourField,
  type DurationField,
  type EnumField,
  type FieldDescriptor,
  type FieldKind,
  type FieldMetadata,
  fieldDescriptorSchema,
  type NumberField,
  protonFields,
  type RoleIdField,
  type ShowWhen,
  type StringField,
  UnsupportedSchemaError,
  zodToDescriptors,
} from './config/descriptor.ts';
export {
  durationStringSchema,
  formatDuration,
  InvalidDurationError,
  parseDuration,
  tryParseDuration,
} from './config/duration.ts';
export { type JsonValue, jsonValueSchema } from './config/json.ts';
export {
  checkLimit,
  checkListLimit,
  LIMIT_KEYS,
  LIMIT_LABELS,
  type LimitCheck,
  type LimitKey,
  limitFor,
  PER_MEMBER_KEYS,
  TIER_LIMITS,
} from './entitlements/limits.ts';
export { createEnv, EnvValidationError } from './env.ts';
export {
  ACHIEVEMENT_JOBS,
  ACHIEVEMENT_RETRY_MAILBOX_PREFIX,
  ACHIEVEMENT_RETRY_MAX,
  ACHIEVEMENT_RETRY_STATUSES,
  type AchievementJob,
  type AchievementJobRequested,
  type AchievementRetryOutcome,
  type AchievementRetryResult,
  type AchievementRetryStatus,
  type AchievementRewardRef,
  type AchievementRewardRetryRequested,
  type AchievementUnlocked,
  achievementJobRequestedSchema,
  achievementRetryOutcomeSchema,
  achievementRetryResultSchema,
  achievementRewardRefSchema,
  achievementRewardRetryRequestedSchema,
  achievementUnlockedSchema,
  TIER_IDS,
  type TierId,
} from './events/achievements.ts';
export {
  APPEAL_DECISIONS,
  type AppealDecided,
  type AppealDecision,
  type AppealSubmitted,
  appealDecidedSchema,
  appealSubmittedSchema,
} from './events/appeals.ts';
export {
  APPLICATION_LIFECYCLE_EVENTS,
  APPLICATION_STATUSES,
  APPLICATION_WORK_REASONS,
  type ApplicationActionFailed,
  type ApplicationLifecycle,
  type ApplicationLifecycleEvent,
  type ApplicationStatus,
  type ApplicationWorkReason,
  type ApplicationWorkRequested,
  applicationActionFailedSchema,
  applicationLifecycleSchema,
  applicationWorkRequestedSchema,
} from './events/applications.ts';
export {
  AUDIT_LOG_EVENT_TYPES,
  type AuditChange,
  type AuditEntry,
  type AuditLogEventPayload,
  type AuditLogEventType,
  auditChange,
  auditChangeSchema,
  auditEntrySchema,
  auditLogEventPayloadSchema,
  isAuditLogEventType,
  requiresAuditLog,
} from './events/audit-log.ts';
export type {
  EventBus,
  GroupStartId,
  SubscribeOptions,
  Subscription,
} from './events/bus.ts';
export {
  CORRELATION_GRACE_MS,
  CORRELATION_PREFIX,
  CORRELATION_TTL_MS,
  type CorrelationStore,
  type CorrelationStoreOptions,
  type PendingLog,
  RedisCorrelationStore,
} from './events/correlation.ts';
export {
  type GiveawayBonusGrantedEvent,
  type GiveawayCancelledEvent,
  type GiveawayCreatedEvent,
  type GiveawayDropClaimedEvent,
  type GiveawayEditedEvent,
  type GiveawayEndedEvent,
  type GiveawayEnteredEvent,
  type GiveawayPausedEvent,
  type GiveawayRerolledEvent,
  type GiveawayResumedEvent,
  type GiveawayStartedEvent,
  giveawayBonusGrantedEventSchema,
  giveawayCancelledEventSchema,
  giveawayCreatedEventSchema,
  giveawayDropClaimedEventSchema,
  giveawayEditedEventSchema,
  giveawayEndedEventSchema,
  giveawayEnteredEventSchema,
  giveawayPausedEventSchema,
  giveawayRerolledEventSchema,
  giveawayResumedEventSchema,
  giveawayStartedEventSchema,
} from './events/giveaways.ts';
export {
  JOINROLES_RUN_KINDS,
  type JoinrolesRunKind,
  type JoinrolesSyncRequested,
  joinrolesSyncRequestedSchema,
} from './events/joinroles.ts';
export {
  type ModerationPunishmentExpired,
  type ModerationReportActionRequested,
  type ModerationReportResolved,
  type ModerationReportSubmitted,
  moderationPunishmentExpiredSchema,
  moderationReportActionRequestedSchema,
  moderationReportResolvedSchema,
  moderationReportSubmittedSchema,
  REPORT_ACTIONS,
  REPORT_METHODS,
  REPORT_STATUSES,
  type ReportAction,
  type ReportActionOutcome,
  type ReportActionParams,
  type ReportMethod,
  type ReportStatus,
  reportActionOutcomeSchema,
  reportActionParamsSchema,
} from './events/moderation.ts';
export {
  COMMAND_CHANGES,
  type CommandChange,
  diffKeys,
  isModerationActionKind,
  MODERATION_ACTION_KINDS,
  type ModerationActionKind,
  type ProtonActionExecuted,
  type ProtonCommandsChanged,
  type ProtonConfigChanged,
  type ProtonPanelRequested,
  type ProtonSecurityTripped,
  protonActionExecutedSchema,
  protonCommandsChangedSchema,
  protonConfigChangedSchema,
  protonPanelRequestedSchema,
  protonSecurityTrippedSchema,
} from './events/proton.ts';
export {
  DLQ_PREFIX,
  dlqKey,
  RedisStreamsEventBus,
  type RedisStreamsEventBusOptions,
  STREAM_PREFIX,
  streamKey,
} from './events/redis-streams.ts';
export {
  type StarboardMessagePosted,
  starboardMessagePostedSchema,
} from './events/starboard.ts';
export {
  TICKET_OPEN_OUTCOMES,
  TICKET_PRIORITIES,
  type TicketClaimedEvent,
  type TicketClosedEvent,
  type TicketDeletedEvent,
  type TicketOpenAnswered,
  type TicketOpenedEvent,
  type TicketOpenOutcome,
  type TicketOpenRequested,
  type TicketPriority,
  type TicketReopenedEvent,
  type TicketSource,
  ticketClaimedEventSchema,
  ticketClosedEventSchema,
  ticketDeletedEventSchema,
  ticketOpenAnsweredSchema,
  ticketOpenedEventSchema,
  ticketOpenRequestedSchema,
  ticketReopenedEventSchema,
  ticketSourceSchema,
} from './events/tickets.ts';
export {
  EVENT_TYPES,
  type EventType,
  isEventType,
  type ProtonEvent,
  SERVICE_EMITTED_EVENT_TYPES,
  type ServiceEmittedEventType,
} from './events/types.ts';
export {
  type VerificationWebPassed,
  verificationWebPassedSchema,
} from './events/verification.ts';
export {
  CAUSATION_KINDS,
  type Causation,
  type CausationKind,
  causationSchema,
  XP_GRANT_MAX,
  XP_GRANT_STATUSES,
  XP_SOURCES,
  type XpAwarded,
  type XpGranted,
  type XpGrantRequested,
  type XpGrantStatus,
  type XpLevelGained,
  type XpSource,
  xpAwardedSchema,
  xpGrantedSchema,
  xpGrantRequestedSchema,
  xpLevelGainedSchema,
} from './events/xp.ts';
export {
  ACTOR_ROLE_REFUSAL_CODES,
  type ActorRoleRefusal,
  type ActorRoleRefusalCode,
  type ActorRoleRefusalInput,
  actorRoleRefusal,
} from './guild-state/actor-roles.ts';
export {
  buildGuildState,
  parseChannel,
  parseGuildProfile,
  parseOverwrites,
  parseRole,
} from './guild-state/build.ts';
export { GUILD_STATE_PREFIX, RedisGuildStateStore } from './guild-state/redis.ts';
export {
  ROLE_GRANT_REFUSAL_CODES,
  type RoleGrantRefusal,
  type RoleGrantRefusalCode,
  roleGrantRefusal,
} from './guild-state/roles.ts';
export {
  type ChannelState,
  type GuildState,
  type GuildStatePatch,
  type GuildStateStore,
  highestRolePosition,
} from './guild-state/types.ts';
export {
  CASE_ID_ALPHABET,
  CASE_ID_LENGTH,
  DISCORD_EPOCH_MS,
  newCaseId,
  newId,
  snowflakeCreatedAt,
} from './ids.ts';
export {
  CUSTOM_ID_SEPARATOR,
  type EncodeCustomIdResult,
  encodeCustomId,
  type ProtonCustomId,
  parseCustomId,
} from './interactions/custom-id.ts';
export {
  type AutocompleteInteraction,
  attachmentExpiry,
  type ComponentInteraction,
  type FocusedOption,
  type InteractionBase,
  type ModalInteraction,
  type ResolvedAttachment,
  type ResolvedData,
  type ResolvedMember,
  type ResolvedMessage,
  type ResolvedUser,
  readAutocompleteInteraction,
  readComponentInteraction,
  readMemberPermissions,
  readModalInteraction,
  readResolved,
  toResolvedMessage,
} from './interactions/read.ts';
export {
  defer,
  deferEphemeral,
  deferUpdate,
  editOriginal,
  type FollowUpTo,
  followUp,
  type InteractionMessage,
  type InteractionRef,
  interactionRef,
  MESSAGE_CONTENT_MAX,
  type MessageInput,
  openModal,
  type RespondTo,
  replyEphemeral,
  respondAutocomplete,
  updateMessage,
} from './interactions/respond.ts';
export {
  LEADERBOARD_PAGE_SIZE_DEFAULT,
  LEADERBOARD_PAGE_SIZE_MAX,
  type LeaderboardQuery,
  type LeaderboardQueryInput,
  type LeaderboardResult,
  type LeaderboardRow,
  leaderboardQuerySchema,
} from './leaderboard.ts';
export { REPORT_ACTION_MAILBOX_PREFIX, RedisMailbox } from './mailbox.ts';
export {
  ACTION_ROWS_MAX,
  type ActionRow,
  actionRowSchema,
  actionRowsSchema,
  BUTTON_LABEL_MAX,
  BUTTON_STYLE_VALUES,
  BUTTON_STYLES,
  BUTTON_URL_MAX,
  BUTTONS_PER_ROW_MAX,
  type ButtonStyle,
  COMPONENT_KEY_MAX,
  type ComponentAction,
  type ComponentEmoji,
  type CustomIdFor,
  componentActionSchema,
  componentEmojiSchema,
  componentKeySchema,
  type DiscordComponent,
  findComponentAction,
  formatComponentEmoji,
  type MessageButton,
  type MessageSelect,
  messageButtonSchema,
  messageSelectSchema,
  parseComponentEmoji,
  REPLY_ACTION_CONTENT_MAX,
  ROLE_ACTION_MODES,
  type RoleActionMode,
  rowKeys,
  SELECT_OPTION_DESCRIPTION_MAX,
  SELECT_OPTION_LABEL_MAX,
  SELECT_OPTIONS_MAX,
  SELECT_PLACEHOLDER_MAX,
  type SelectOption,
  selectOptionSchema,
  toDiscordComponents,
} from './messages/components.ts';
export {
  type CachedAttachment,
  type CachedMessage,
  cachedAttachmentSchema,
  cachedMessageSchema,
  clampCacheTtl,
  MESSAGE_CACHE_ATTACHMENTS_MAX,
  MESSAGE_CACHE_CONTENT_MAX,
  MESSAGE_CACHE_DEFAULT_TTL_MS,
  MESSAGE_CACHE_MAX_TTL_MS,
  MESSAGE_CACHE_MIN_TTL_MS,
  MESSAGE_CACHE_PREFIX,
  type MessageContentCache,
  RedisMessageContentCache,
  type RedisMessageContentCacheOptions,
  toCachedMessage,
} from './messages/content-cache.ts';
export {
  type DiscordEmbed,
  type DiscordEmbedField,
  EMBED_AUTHOR_NAME_MAX,
  EMBED_COLOR_MAX,
  EMBED_DESCRIPTION_MAX,
  EMBED_FIELD_NAME_MAX,
  EMBED_FIELD_VALUE_MAX,
  EMBED_FIELDS_MAX,
  EMBED_FOOTER_TEXT_MAX,
  EMBED_TITLE_MAX,
  EMBED_TOTAL_MAX,
  EMBED_URL_MAX,
  EMBEDS_PER_MESSAGE_MAX,
  type Embed,
  type EmbedAuthor,
  type EmbedField,
  type EmbedFooter,
  embedAuthorSchema,
  embedFieldSchema,
  embedFooterSchema,
  embedLength,
  embedLinkSchema,
  embedSchema,
  embedsLength,
  isEmptyEmbed,
  toDiscordEmbed,
} from './messages/embed.ts';
export { messageUrl, type ParsedMessageLink, parseMessageLink } from './messages/link.ts';
export {
  DEFAULT_MENTION_POLICY,
  type DiscordMessageBody,
  EMPTY_MESSAGE,
  interactiveKeys,
  isComponentsV2,
  liftLegacyMessage,
  type MentionPolicy,
  mentionPolicySchema,
  messageObjectSchema,
  messageSchema,
  messageShape,
  type ProtonMessage,
  refineMessage,
  storedMessageSchema,
  type ToDiscordMessageOptions,
  toAllowedMentions,
  toDiscordMessage,
} from './messages/message.ts';
export {
  BOOST_MESSAGE_TYPES,
  HUMAN_MESSAGE_TYPES,
  isBoostMessageType,
  isHumanMessage,
} from './messages/message-type.ts';
export {
  errorEmbed,
  errorStatus,
  isStatusBody,
  STATUS_ERROR_COLOUR,
  STATUS_ERROR_EMOJI,
  STATUS_SUCCESS_COLOUR,
  STATUS_SUCCESS_EMOJI,
  type StatusBody,
  type StatusEmbed,
  type StatusKind,
  statusBody,
  statusEmbed,
  successEmbed,
  successStatus,
} from './messages/status.ts';
export {
  type MessageTemplate,
  messageTemplateSchema,
  type RenderedTemplate,
  renderTemplate,
  substitute,
  type TemplateVars,
} from './messages/template.ts';
export {
  COMPONENT_TYPE_CONTAINER,
  COMPONENT_TYPE_MEDIA_GALLERY,
  COMPONENT_TYPE_SECTION,
  COMPONENT_TYPE_SEPARATOR,
  COMPONENT_TYPE_TEXT_DISPLAY,
  COMPONENT_TYPE_THUMBNAIL,
  CONTAINER_ACCENT_MAX,
  type ContainerChild,
  containerChildSchema,
  containerSchema,
  countV2Components,
  MEDIA_DESCRIPTION_MAX,
  MEDIA_GALLERY_ITEMS_MAX,
  type MediaItem,
  mediaGallerySchema,
  mediaItemSchema,
  SECTION_TEXT_MAX,
  SEPARATOR_SPACING_VALUES,
  SEPARATOR_SPACINGS,
  type SectionAccessory,
  type SeparatorSpacing,
  sectionAccessorySchema,
  sectionSchema,
  separatorSchema,
  textDisplaySchema,
  toDiscordV2Components,
  V2_COMPONENTS_MAX,
  type V2Component,
  v2AccessoryButtons,
  v2ComponentSchema,
  v2ComponentsSchema,
  v2Rows,
} from './messages/v2.ts';
export {
  type BotInvite,
  botInviteSchema,
  COMMAND_SYNC_STATES,
  type CommandCatalogueView,
  type CommandEnabledBody,
  type CommandSettingsView,
  type CommandSyncFailure,
  type CommandSyncState,
  type CommandSyncView,
  type CommandUpdateBody,
  type CommandUpdateResult,
  type CommandView,
  type CommandWorkerView,
  commandCatalogueViewSchema,
  commandEnabledBodySchema,
  commandSettingsViewSchema,
  commandSyncFailureSchema,
  commandSyncViewSchema,
  commandUpdateBodySchema,
  commandUpdateResultSchema,
  commandViewSchema,
  commandWorkerViewSchema,
  type GuildOverview,
  type GuildPresence,
  guildOverviewSchema,
  guildPresenceSchema,
  type LostCommandPermissions,
  lostCommandPermissionsSchema,
  type ModuleConfigView,
  type ModuleField,
  type ModuleIndex,
  type ModuleSection,
  type ModuleStatusView,
  type ModuleSummary,
  type ModuleUpdateResult,
  moduleConfigViewSchema,
  moduleFieldSchema,
  moduleIndexSchema,
  moduleSectionSchema,
  moduleStatusSchema,
  moduleSummarySchema,
  moduleUpdateResultSchema,
  type PanelRequestResult,
  panelRequestResultSchema,
  postableSchema,
  type VerificationRequestResult,
  verificationRequestResultSchema,
} from './modules/api-io.ts';
export type {
  CommandContext,
  CommandDefinition,
  ConfigLimit,
  ConfigWriteIssue,
  ContextMenuContext,
  ContextMenuDefinition,
  ContextMenuType,
  EventListener,
  Logger,
  ModuleCategory,
  ModuleContext,
  ModuleManifest,
  Postable,
  ScheduledHandler,
  SectionDescriptor,
} from './modules/manifest.ts';
export {
  type CommandOptions,
  CommandOptionTypeError,
  createCommandOptions,
  OptionType,
  type RawOption,
} from './modules/options.ts';
export {
  type DisabledCode,
  MAX_CHAT_COMMANDS,
  MAX_CONTEXT_MENUS_PER_TYPE,
  ModuleRegistrationError,
  ModuleRegistry,
  type ModuleRegistryOptions,
  type ModuleStatus,
  type RegistryEnvironment,
  UndeclaredScheduleError,
} from './modules/registry.ts';
export {
  type ChannelAudience,
  type ChannelAudienceInput,
  channelAudience,
} from './permissions/audience.ts';
export {
  ALL_PERMISSIONS,
  combinePermissions,
  has,
  hasWithAdmin,
  missing,
  Permissions,
  permissionLabel,
  permissionLabels,
  permissionNames,
} from './permissions/bits.ts';
export {
  applyOverwrites,
  computeBasePermissions,
  computeChannelPermissions,
  type GuildRole,
  type Overwrite,
  type PermissionContext,
} from './permissions/compute.ts';
export * from './providers/index.ts';
export {
  countLeaves,
  depthOf,
  describeTree,
  distinctLeaves,
  evaluateTree,
  isGroup,
  leafKey,
  type RequirementGroup,
  type RequirementLeaf,
  type RequirementNode,
  requirementTreeSchema,
  TREE_LOGICS,
  TREE_MAX_CHILDREN,
  TREE_MAX_DEPTH,
  TREE_MAX_LEAVES,
  type TreeLogic,
  type TreeOptions,
  type TreeVerdict,
  treeFromFlat,
} from './providers/tree.ts';
// Not re-exported here: redis.ts constructs an ioredis client, and this barrel is imported by
// dashboard components. Re-exporting put ioredis in the browser bundle, where it threw on load and
// left the whole dashboard server-rendered but never hydrated. Import '@proton/core/redis'.
export {
  evaluateFactCondition,
  type FactCondition,
  type FactConditionResult,
  LEGACY_MEMBER_CONDITION_KINDS,
  type LegacyMemberConditionKind,
  MAX_PATTERN_LENGTH,
  type ProviderCondition,
  type RateOverWindowCondition,
  RULE_CONDITION_KINDS,
  type RuleCondition,
  type RuleConditionKind,
  ruleConditionSchema,
} from './rules/conditions.ts';
export {
  RULE_ENGINE_ACTOR,
  type RuleActionOutcome,
  RuleEngine,
  type RuleEngineDeps,
  type RuleEvaluationInput,
  type RuleEvaluationReport,
  type RuleFireInput,
  type RuleOutcome,
  type RuleSkip,
  type RuleSkipCode,
} from './rules/engine.ts';
export {
  ENTITLEMENT_TIERS,
  type EntitlementTier,
  entitlementRank,
  type RuleFacts,
} from './rules/facts.ts';
export {
  isLegacyMemberCondition,
  LEGACY_CONDITION_PROVIDERS,
  migrateCondition,
  migrateRuleConditions,
} from './rules/migrate.ts';
export {
  crossedKeyFor,
  moveRateWindows,
  RATE_WINDOW_GUILD_SCOPE,
  RATE_WINDOW_PREFIX,
  type RateWindowHit,
  type RateWindowMove,
  type RateWindowResult,
  type RateWindowStore,
  RedisRateWindow,
  type RedisRateWindowOptions,
  rateWindowKey,
} from './rules/rate-window.ts';
export {
  type GuildRule,
  guildRuleSchema,
  type RuleAction,
  type RuleDefinition,
  type RuleTrigger,
  ruleActionSchema,
  ruleDefinitionSchema,
  ruleTriggerSchema,
  type ScheduledJob,
} from './rules/types.ts';
export {
  readLink,
  SIGNED_LINK_SECRET_MIN,
  type SignedLinkClaims,
  type SignedLinkResult,
  signLink,
} from './signed-link.ts';
export {
  asTestDelivery,
  displayNameOf,
  markerFor,
  messageLink,
  pathDiagnosticSchema,
  personFor,
  RedisSimulationResults,
  readBoolean,
  readChoice,
  readInteger,
  readText,
  SIMULATION_ACTOR,
  SIMULATION_DELIVERIES,
  SIMULATION_INPUT_KINDS,
  SIMULATION_MODES,
  SIMULATION_MODULE_ID,
  SIMULATION_OUTPUTS,
  SIMULATION_RESULT_PREFIX,
  SIMULATION_RESULT_TTL_MS,
  SIMULATION_WAIT_MS,
  type SimulationAdapter,
  type SimulationAttachment,
  type SimulationBuild,
  type SimulationCard,
  type SimulationCatalogue,
  type SimulationChoice,
  type SimulationDelivery,
  type SimulationDescriptor,
  type SimulationDestination,
  type SimulationInput,
  type SimulationInputKind,
  type SimulationInputValue,
  type SimulationMode,
  type SimulationOutcome,
  type SimulationOutput,
  type SimulationOutputKind,
  type SimulationPerson,
  type SimulationRender,
  type SimulationRequestedPayload,
  type SimulationResults,
  type SimulationRun,
  type SimulationScene,
  type SimulationSent,
  simulationAttachmentSchema,
  simulationCardQuery,
  simulationCardSchema,
  simulationCatalogueSchema,
  simulationDescriptorSchema,
  simulationDestinationSchema,
  simulationInputDefaults,
  simulationInputSchema,
  simulationInputsSchema,
  simulationOutcomeSchema,
  simulationRenderSchema,
  simulationRequestedPayloadSchema,
  simulationRunSchema,
  simulationSentSchema,
  type TestDeliveryResult,
  testCustomIdFor,
  UNRESOLVED_CODES,
  unavailableMember,
  unresolvedDiagnostics,
} from './simulation/index.ts';
export { CSV_FORMULA_LEADS, type CsvValue, csvCell, toCsv } from './text/csv.ts';
export {
  DOMAIN_MAX_LENGTH,
  domainCandidates,
  extractHosts,
  firstMatch,
  type HostCandidates,
  MAX_HOSTS_PER_MESSAGE,
  MAX_SUFFIXES_PER_HOST,
  messageCandidates,
  normaliseDomain,
  toDomainSet,
} from './text/domains.ts';
export { type GuildMemberRead, readGuildMember } from './users/guild-member.ts';
export {
  avatarUrl,
  CDN_BASE,
  RedisUserProfileCache,
  toUserProfile,
  USER_PROFILE_PREFIX,
  USER_PROFILE_TTL_MS,
  type UserProfile,
  type UserProfileCache,
  userProfileSchema,
} from './users/profile-cache.ts';
export {
  createUserResolver,
  isPseudoActor,
  PSEUDO_ACTOR_PREFIX,
  type UserResolver,
  type UserResolverDeps,
} from './users/resolver.ts';
export {
  newVerifyLinkClaims,
  readVerifyLink,
  signVerifyLink,
  VERIFY_LINK_SECRET_MIN,
  VERIFY_LINK_TTL_MS,
  type VerifyLinkClaims,
  type VerifyLinkResult,
  verifyLinkClaimsSchema,
} from './verify-link.ts';
export {
  RedisVoiceSessionStore,
  type RedisVoiceSessionStoreOptions,
} from './voice/redis-session-store.ts';
export {
  MAX_VOICE_STAY_MS,
  type VoiceSession,
  type VoiceSessionStore,
  voiceSessionKey,
  voiceSessionSchema,
} from './voice/session.ts';
export {
  isVoiceEligible,
  readVoiceState,
  type VoiceEligibilityOptions,
  type VoiceState,
} from './voice/state.ts';
