// Generated by scripts/build-registry.ts. Do not edit by hand.

import type { ModuleSummary } from '@proton/core';
import type { ComponentType } from 'react';
import type { ModuleMeta } from '../../lib/modules/catalogue.ts';

export interface ModulePageProps {
  guildId: string;
  meta: ModuleMeta;
  summary: ModuleSummary | undefined;
  area: string;
}

export type ModulePage = ComponentType<ModulePageProps>;
