// Generated by scripts/build-registry.ts from the files in src/pages. Do not edit by hand.
// Re-run with `bun run build:registry` after adding a module page.

import type { ModuleSummary } from '@proton/core';
import type { ComponentType } from 'react';
import { lazy } from 'react';
import type { ModuleMeta } from '../../lib/modules/catalogue.ts';

export interface ModulePageProps {
  guildId: string;
  meta: ModuleMeta;
  summary: ModuleSummary | undefined;
  /** The resolved area, already defaulted to the module's first when the URL named none. */
  area: string;
}

export type ModulePage = ComponentType<ModulePageProps>;

/**
 * One lazy entry per module, so a settings page carries only its own module's schema into the
 * browser rather than all thirty.
 * Every module has one.
 */
const PAGES: Record<string, () => Promise<{ default: ModulePage }>> = {
  antinuke: () => import('../../pages/antinuke.tsx'),
  antiraid: () => import('../../pages/antiraid.tsx'),
  appeals: () => import('../../pages/appeals.tsx'),
  automod: () => import('../../pages/automod.tsx'),
  backup: () => import('../../pages/backup.tsx'),
  branding: () => import('../../pages/branding.tsx'),
  cases: () => import('../../pages/cases.tsx'),
  counters: () => import('../../pages/counters.tsx'),
  giveaways: () => import('../../pages/giveaways.tsx'),
  help: () => import('../../pages/help.tsx'),
  honeypot: () => import('../../pages/honeypot.tsx'),
  joinroles: () => import('../../pages/joinroles.tsx'),
  leveling: () => import('../../pages/leveling.tsx'),
  logging: () => import('../../pages/logging.tsx'),
  messages: () => import('../../pages/messages.tsx'),
  moderation: () => import('../../pages/moderation.tsx'),
  permissions: () => import('../../pages/permissions.tsx'),
  phishing: () => import('../../pages/phishing.tsx'),
  ping: () => import('../../pages/ping.tsx'),
  polls: () => import('../../pages/polls.tsx'),
  reminders: () => import('../../pages/reminders.tsx'),
  rolemenu: () => import('../../pages/rolemenu.tsx'),
  serverlog: () => import('../../pages/serverlog.tsx'),
  starboard: () => import('../../pages/starboard.tsx'),
  suggestions: () => import('../../pages/suggestions.tsx'),
  tags: () => import('../../pages/tags.tsx'),
  tempvc: () => import('../../pages/tempvc.tsx'),
  tickets: () => import('../../pages/tickets.tsx'),
  verification: () => import('../../pages/verification.tsx'),
  welcome: () => import('../../pages/welcome.tsx'),
};

const CACHE = new Map<string, ModulePage>();

export function modulePage(moduleId: string): ModulePage | null {
  const loader = PAGES[moduleId];
  if (!loader) return null;

  const held = CACHE.get(moduleId);
  if (held) return held;

  const component = lazy(loader);
  CACHE.set(moduleId, component);
  return component;
}

export function hasModulePage(moduleId: string): boolean {
  return PAGES[moduleId] !== undefined;
}
