-- `rules.trigger` becomes jsonb, because `RuleTrigger` stopped being a string.
--
-- The column was created as text when a trigger was just an event type. The
-- trigger is now a discriminated union — `{kind:'event', event}` or
-- `{kind:'cron', cron, timezone?}` — and a text column cannot hold the cron
-- variant without dropping `cron` and `timezone` or inventing an encoding that
-- `ruleTriggerSchema` does not describe.
--
-- Generated by drizzle-kit, then edited: it emits a bare SET DATA TYPE for the
-- text -> jsonb change, and Postgres has no assignment cast between those two,
-- so the unedited statement fails at plan time on an empty table just as it
-- would on a full one. The USING clause below is the whole point of the edit.
DROP INDEX "rules_guild_trigger_idx";--> statement-breakpoint
-- Nothing writes this table yet (the Gate 0 comment on the Drizzle object says
-- so), but the conversion is written out rather than assumed: any row already
-- there holds a bare event-type discriminator, which is exactly the `event`
-- variant with its `kind` left implicit. A value that was never a valid event
-- type converts too and is rejected later by `guildRuleSchema` on load, which is
-- the designed path for an unparseable rule — not silently dropped here.
ALTER TABLE "rules" ALTER COLUMN "trigger" SET DATA TYPE jsonb
  USING jsonb_build_object('kind', 'event', 'event', "trigger");--> statement-breakpoint
-- The event type, lifted back out so the dispatch lookup stays a btree probe
-- instead of a jsonb comparison. GENERATED ALWAYS rather than a second column
-- the application maintains: Postgres derives it, so it cannot disagree with
-- `trigger`. NULL for a cron rule, which is what keeps cron rules out of event
-- dispatch. The `kind` guard means a row that carries an `event` key alongside
-- `kind = 'cron'` — reachable only by a writer that skipped the Zod schema —
-- does not get enrolled in event dispatch on the strength of a stray key.
ALTER TABLE "rules" ADD COLUMN "trigger_event" text GENERATED ALWAYS AS (case when "trigger" ->> 'kind' = 'event' then "trigger" ->> 'event' end) STORED;--> statement-breakpoint
CREATE INDEX "rules_guild_trigger_event_idx" ON "rules" USING btree ("guild_id","trigger_event");
