-- The leaderboard index (PLAN.md §6, docs/PHASE-3.md G7).
--
-- `members` has existed and gone unwritten since Gate 0. Phase 3 turns it into
-- the hottest table in the system — one row per member per guild, written once
-- per message per cooldown window — and gives it exactly one query that scans
-- rather than probes:
--
--     select user_id, xp from members
--      where guild_id = $1 and xp > 0
--      order by xp desc, user_id asc
--      limit $2 offset $3
--
-- The primary key is (guild_id, user_id), which answers `/rank` and every write
-- but is useless for that ordering: without this index a guild's board is a heap
-- scan plus a sort of every member who ever spoke, on a table that grows with
-- every member of every guild Proton is in.
--
-- Hand-written rather than generated, because the Drizzle table object carries
-- no index declaration and adding one there would make the next `drizzle-kit
-- generate` emit this a second time. `IF NOT EXISTS` so re-running the migration
-- set against a database that already has it is a no-op rather than an error.
--
-- Ordered on xp DESC to match the query's direction. The tie-break on user_id is
-- deliberately not part of the index: it only orders members holding *identical*
-- XP, which Postgres settles with a small sort inside each tied group, and
-- carrying a third column through every insert to save that is the wrong trade
-- on the write path this table actually lives on.
CREATE INDEX IF NOT EXISTS "members_guild_xp_idx" ON "members" USING btree ("guild_id","xp" DESC);
