/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuildsIndexRouteImport } from './routes/guilds.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as GuildsGuildIdModulesModuleIdRouteImport } from './routes/guilds.$guildId.modules.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsIndexRoute = GuildsIndexRouteImport.update({
  id: '/guilds/',
  path: '/guilds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuildsGuildIdModulesModuleIdRoute =
  GuildsGuildIdModulesModuleIdRouteImport.update({
    id: '/guilds/$guildId/modules/$moduleId',
    path: '/guilds/$guildId/modules/$moduleId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guilds/': typeof GuildsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/$guildId/modules/$moduleId': typeof GuildsGuildIdModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guilds': typeof GuildsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/$guildId/modules/$moduleId': typeof GuildsGuildIdModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guilds/': typeof GuildsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/$guildId/modules/$moduleId': typeof GuildsGuildIdModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/guilds/' | '/api/auth/$' | '/guilds/$guildId/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guilds' | '/api/auth/$' | '/guilds/$guildId/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/guilds/'
    | '/api/auth/$'
    | '/guilds/$guildId/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuildsIndexRoute: typeof GuildsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GuildsGuildIdModulesModuleIdRoute: typeof GuildsGuildIdModulesModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/': {
      id: '/guilds/'
      path: '/guilds'
      fullPath: '/guilds/'
      preLoaderRoute: typeof GuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guilds/$guildId/modules/$moduleId': {
      id: '/guilds/$guildId/modules/$moduleId'
      path: '/guilds/$guildId/modules/$moduleId'
      fullPath: '/guilds/$guildId/modules/$moduleId'
      preLoaderRoute: typeof GuildsGuildIdModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuildsIndexRoute: GuildsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GuildsGuildIdModulesModuleIdRoute: GuildsGuildIdModulesModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
