/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard/$guildId'
import { Route as VerifyTokenRouteImport } from './routes/verify/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DashboardGuildIdModuleIdRouteImport } from './routes/dashboard/$guildId/$moduleId'
import { Route as ApiAuthSigninDiscordRouteImport } from './routes/api/auth/signin/discord'
import { Route as ApiGuildsGuildIdCardPreviewRouteImport } from './routes/api/guilds/$guildId/card-preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/dashboard/$guildId',
  path: '/dashboard/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdModuleIdRoute =
  DashboardGuildIdModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const ApiAuthSigninDiscordRoute = ApiAuthSigninDiscordRouteImport.update({
  id: '/api/auth/signin/discord',
  path: '/api/auth/signin/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildsGuildIdCardPreviewRoute =
  ApiGuildsGuildIdCardPreviewRouteImport.update({
    id: '/api/guilds/$guildId/card-preview',
    path: '/api/guilds/$guildId/card-preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/verify/$token': typeof VerifyTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$guildId/$moduleId': typeof DashboardGuildIdModuleIdRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/auth/signin/discord': typeof ApiAuthSigninDiscordRoute
  '/api/guilds/$guildId/card-preview': typeof ApiGuildsGuildIdCardPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$guildId/$moduleId': typeof DashboardGuildIdModuleIdRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/api/auth/signin/discord': typeof ApiAuthSigninDiscordRoute
  '/api/guilds/$guildId/card-preview': typeof ApiGuildsGuildIdCardPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/verify/$token': typeof VerifyTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$guildId/$moduleId': typeof DashboardGuildIdModuleIdRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/auth/signin/discord': typeof ApiAuthSigninDiscordRoute
  '/api/guilds/$guildId/card-preview': typeof ApiGuildsGuildIdCardPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/dashboard/$guildId'
    | '/verify/$token'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/$guildId/$moduleId'
    | '/dashboard/$guildId/'
    | '/api/auth/signin/discord'
    | '/api/guilds/$guildId/card-preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/verify/$token'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/$guildId/$moduleId'
    | '/dashboard/$guildId'
    | '/api/auth/signin/discord'
    | '/api/guilds/$guildId/card-preview'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/dashboard/$guildId'
    | '/verify/$token'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/$guildId/$moduleId'
    | '/dashboard/$guildId/'
    | '/api/auth/signin/discord'
    | '/api/guilds/$guildId/card-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
  VerifyTokenRoute: typeof VerifyTokenRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSigninDiscordRoute: typeof ApiAuthSigninDiscordRoute
  ApiGuildsGuildIdCardPreviewRoute: typeof ApiGuildsGuildIdCardPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/$moduleId': {
      id: '/dashboard/$guildId/$moduleId'
      path: '/$moduleId'
      fullPath: '/dashboard/$guildId/$moduleId'
      preLoaderRoute: typeof DashboardGuildIdModuleIdRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/api/auth/signin/discord': {
      id: '/api/auth/signin/discord'
      path: '/api/auth/signin/discord'
      fullPath: '/api/auth/signin/discord'
      preLoaderRoute: typeof ApiAuthSigninDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guilds/$guildId/card-preview': {
      id: '/api/guilds/$guildId/card-preview'
      path: '/api/guilds/$guildId/card-preview'
      fullPath: '/api/guilds/$guildId/card-preview'
      preLoaderRoute: typeof ApiGuildsGuildIdCardPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdModuleIdRoute: typeof DashboardGuildIdModuleIdRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdModuleIdRoute: DashboardGuildIdModuleIdRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
  VerifyTokenRoute: VerifyTokenRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSigninDiscordRoute: ApiAuthSigninDiscordRoute,
  ApiGuildsGuildIdCardPreviewRoute: ApiGuildsGuildIdCardPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
